### ISSUE TITLE
JreTypeSolver encounters NullPointerException when added to bootstrap classpath

### ISSUE THREAD

**Issue by emanguy** [javaparser/javasymbolsolver#10]
On line 27 of JreTypeSolver, when you run

``` java
Class<?> clazz = JreTypeSolver.class.getClassLoader().loadClass(name);
```

and you import the code through the bootstrap classpath (i.e. -Xbootclasspath/a:path), `getClassLoader()` will return null as per https://docs.oracle.com/javase/8/docs/api/java/lang/Class.html#getClassLoader--.

**Comment by ftomassetti** [comment]
Thanks for reporting this!
