### ISSUE TITLE
Uniform the build system to JavaParser

### ISSUE THREAD

**Issue by ftomassetti** [javaparser/javasymbolsolver#101]
We currently have both Maven and Gradle, we should use just one.

JavaParser is using Maven, so maybe we could just move to Maven. Or keep Gradle and remove Maven.

Currently maven is just used to produce the packages used to do releases...

**Comment by matozoid** [comment]
I've spent too damn much time on the release plugin to want to touch the build system again. Will accept a PR though :) Currently I can do a release with mvn release:clean,prepare,perform, and a little clicking around on bintray.

I figured out bintray + gradle once: https://github.com/laamella-gad/file-index/blob/master/build.gradle

**Comment by ftomassetti** [comment]
In the end I removed Maven and wrote a script to package things. Once I have the packages I just upload them manually on sonatype nexus.

**Comment by matozoid** [comment]
With the chaos I created with the code generation I was considering moving to Gradle...
