### ISSUE TITLE
 Adopt the JavaParser code style

### ISSUE THREAD

**Issue by ftomassetti** [javaparser/javasymbolsolver#103]

**Comment by matozoid** [comment]
You mean the formatter?

**Comment by ftomassetti** [comment]
I mean adopting the formatter and using it to reformat all code

**Comment by matozoid** [comment]
Somewhat connected to https://github.com/javaparser/javaparser/issues/424 then.

**Comment by matozoid** [comment]
So you managed to format symbol solver before javaparser got to it? :-O

**Comment by ftomassetti** [comment]
Apparently :D
This is a little, rogue project, I can get things done more easily :D
