### ISSUE TITLE
Solve type for Field Access Expression

### ISSUE THREAD

**Issue by mhepaixao** [javaparser/javasymbolsolver#118]
First of all, congrats for this project, it's been really useful in a research project I'm executing. I'm currently solving types of method calls without much problems, but I was wondering if there is any way to solve the type for a FieldAccesExpr? Thanks.

**Comment by mlangkabel** [comment]
Hi @mhepaixao! Glad to hear that you like it :)

I think you can just call 

```java
JavaParserFacade.get(typeSolver).getType(fieldAccessExpr);
```

So you just need to use a typeSolver that knows the declaration of the Field you are using and hand over the fieldAccessExpr node that you get from the JavaParser's AST
