### ISSUE TITLE
Unable to solve type of a variable declared in the resource of try-with-resource

### ISSUE THREAD

**Issue by xinan** [javaparser/javasymbolsolver#119]
```
try (Scanner sc = new Scanner(System.in)) {
    sc.nextLine();
}
```

When I tried to solve the type of the scope of the `MethodCallExpr` (`sc.nextLine()`), a `UnsolvedSymbolException` was thrown. I think `try-with-resource` was not taken into account.

**Comment by ftomassetti** [comment]
Yes, it is not taken into account. I will implement it. Thank you so much for reporting this one!

**Comment by ftomassetti** [comment]
Implemented
