### ISSUE TITLE
Unable to solve call to method declared in Class.MemberClass

### ISSUE THREAD

**Issue by mlangkabel** [javaparser/javasymbolsolver#129]
I get a RuntimeException caused by an UnsolvedSymbolException when I try to solve the method called in the following code snippet. 

```
Class.MemberClass.method();
```

When the MethodCallExprContext tries to solve this method it starts with solving the type of the methods scope. Here the JavaParserFacade finds the type of Class and tries to look for a FIELD called MemberClass (I think this is because we are trying to solve a FieldAccessExpr). But MemberClass is not a field. It is a member. So maybe the classes that implement the `ReferenceTypeDeclaration` interface also need a method called `getAllMembers`. What do you think?

It looks like this bug is caused by a naming issue as Javaparser seems to call everything a FieldAccess even if it may be a MemberAccess ;)

**Comment by mlangkabel** [comment]
I just took another look at the issue. We could also add a `getDeclaredTypes` method to the ReferenceTypeDeclaration and call this one in the JavaParserFacade if no field with the required name has been found. So Field and Type would not need to implement a common base ;)

**Comment by mlangkabel** [comment]
Here is an example snippet. To reproduce the issue try to solve the MethodCallExpr to `bar()`
```java
public class JavaTest {
	static class X {
		public static void bar() {
		}
	}

	public void test() {
	    JavaTest.X.bar();
	}
}
```

**Comment by matozoid** [comment]
Note: JavaParser deals with the ambiguity in these kinds of expressions by assuming the most common case. It's not a bug, it's not much of a feature either ;)

**Comment by mlangkabel** [comment]
Ah, so field is more general than member? I always thought it was the other way round. Thanks for clarifying :)

**Comment by staslev** [comment]
+1 for properly handling inner classes and cases such as `ClassX.ClassY.method()`.

While the definition of a bug may lead us to a philosophical discussion, I think we can safely settle for "behaves **NOT** as expected" :)

Is handling cases such as `ClassX.ClassY.method()` something you guys would be willing to consider for the coming releases? 

CC:@ftomassetti

**Comment by matozoid** [comment]
@staslev indeed, and I may have been too vague: it's an ambiguity in the *parser* - the symbol solver should be able to disambiguate this!

**Comment by staslev** [comment]
Great, thanks for the quick reply!

Looking forward to see the fix go live.

**Comment by ftomassetti** [comment]
Maybe member would be a better name in JavaParser, not sure. On one hand in the parser we cannot figure that out so using a generic term like "member" or "symbol" or "thisThingOfWhichNatureIAmNotReallySureAbout" could be more correct but also a bit confusing for newbies.

It is clear however that this should be handled correctly in the JavaSymbolSolver.

At some point we could review naming conventions, looking in particular at how to differentiate things in JavaParser and JavaSymbolSolver.

**Comment by ftomassetti** [comment]
This should work now
