### ISSUE TITLE
Find correct references

### ISSUE THREAD

**Issue by nguyenthanhvuh** [javaparser/javasymbolsolver#131]
Hi, in the below code, can I use JavaSymbolSolver to determine that stRef is just st ?  I know JavaSymbolSolver can determines the type of stRef as Stack, but not sure if it can determine aliasing like this.  Also I want to label this under Question but not sure how to do this.  Thanks,  

```
   Stack st = new Stack();
   Stack stRef = st;
   .....
   st.push("Java");
   st.push("Source");
   stRef.push("code");   //I want to be able to tell that stRef is just st here
      
   System.out.println("Removed object is: "+st.pop());
```

**Comment by ftomassetti** [comment]
First of all thank you for your question.

Unfortunately the answer is no. This is not a feature we currently provide. To provide it would probably require to have some sort of dataflow analysis I guess.

How would you envision such a feature to work?
