### ISSUE TITLE
Java Symbol solver does not resolve bindings of parameters if the classes refers third party library

### ISSUE THREAD

**Issue by ameyaKetkar** [javaparser/javasymbolsolver#134]
I am using JavaSymbolSolver  to infer the parameter type, using binding information. 
I do not have the jars, of the project or the library referenced.What I have is the the source code. 
In the combined type solver i added the reflectionsolver and provided path to the source code of the project. 
I am able to do this using eclipse JDT, but not using javasymbolsolver. I really want to use javasymbol solver since it integrates with javaparser. Here is the link to my implemetatiomn using eclipseJDT:
https://github.com/ameyaKetkar/MethodPArserEclipseJDT
In this repo, in App.java, I first try to get list of all functionalInterfaces declared in the project and then try to look for methodDeclarations which use these functional interfaces by getting the binding information. (This is the requirement of my research)

how can i use javasymbolsolver to address my requirements/

**Comment by ftomassetti** [comment]
This is something supported now
