### ISSUE TITLE
TypeSolver:s not backed by ReflectionTypeSolver gets stuck in infinite recursion

### ISSUE THREAD

**Issue by whizzter** [javaparser/javasymbolsolver#144]
I'm working on transpiler experiment and as such i have my own boot classes and only a single JavaParserTypeSolver.

When resolving the argument for the call in the example below in the solver gets into a infinite recursion at com.github.javaparser.symbolsolver.javaparsermodel.declarations.JavaParserClassDeclaration.getAllFields(JavaParserClassDeclaration.java:113)

Changing the typesolver to a CombinedTypeSolver based on a ReflectionTypeSolver and a JavaParserTypeSolver gets rid of the crash.

```
public class HelloWorld {

	static String hw="Hello world";
	
	public static void main(String[] args) {
		System.out.println(hw);
	}
}
```
(Edits: code block formatting)

**Comment by ftomassetti** [comment]
Thanks for reporting this. This obviously seems a bug, marked for further investigation

**Comment by whizzter** [comment]
Looked a bit more at the problem.

Building the CombinedTypeSolver with the JavaParserTypeSolver before the reflection resolver also causes it to crash. So when it succeeds it calls getAllFields from the reflection model and that method is non-recursive so it doesn't have this problem.

So JavaParserClassDeclaration:getAllFields would thus need to have a check before recursion to see that the current instance isn't already handling java.lang.Object

**Comment by whizzter** [comment]
tryToSolveType in JavaParserTypeSolver is the "last place" the full type name is known.

1: Add a cache of ReferenceTypeDeclaration's in tryToSolveType in JavaParserType solver, this way getAllFields could check that "this != superclass" inside getAllFields.

**Comment by whizzter** [comment]
tryToSolveType in JavaParserTypeSolver is the "last place" the full type name is known.

1: Add a cache of ReferenceTypeDeclaration's in tryToSolveType in JavaParserType solver, this way getAllFields could check that "this != superclass" inside getAllFields.
2: The code that create different kinds of type declarations should be sure that they are also given the full name they were created with (since the parse tree really only has a local name)

PS: Looking at the resolution code i didn't spot anything about inner classes?
