### ISSUE TITLE
Different JavaParserFacade in repo

### ISSUE THREAD

**Issue by tamtam22** [javaparser/javasymbolsolver#147]
Hi,

I'm using this with gradle:
`compile group:'com.github.javaparser', name: 'java-symbol-solver-core', version: '0.4.0'`

Apparently the one on maven is outdated, JavaParserFacade.java (line 653) uses call.getArgs() instead of call.getArguments()

Would be great if the project hosted on maven is in sync with the existing repo version.

**Comment by ftomassetti** [comment]
Right, I need to do a release in next week.

I postponed this for some time because I was working on a large feature in JavaParser. I am now wrapping that up and I will go back to JavaSymbolSolver. As first thing I will do a release.

**Comment by matozoid** [comment]
Just for info: JavaParser itself has a much higher release rate than JavaSymbolSolver, so when using JSS you should use the version of JP that it depends on.
