### ISSUE TITLE
Cannot resolve NameExpr

### ISSUE THREAD

**Issue by tamtam22** [javaparser/javasymbolsolver#154]
Hi,

I am unable to get the qualified name of NameExpr using the code below:

`if(JavaParserFacade.get(getCombinedTypeSolver()).solve((NameExpr) node).isSolved()) { .. }`

The symbol is never solved.

The (NameExpr) node is `Boolean, SSLSocketFactory` etc, and what I want to retrieve is the class name (i.e. `java.lang.Boolean, org.apache.http.conn.ssl.SSLSocketFactory`)

However the solver always return no value/null. How do I go about getting the qualified name of the NameExpr?

**Comment by tamtam22** [comment]
After tinkering for about 2 hours i managed to get this working with:

`JavaParserFacade.get(getCombinedTypeSolver()).getSymbolSolver().solveType(((NameExpr) node).getNameAsString(), node).getCorrespondingDeclaration().getQualifiedName()`

Of course you need to check if it isSolved() first. Again not sure if this is the correct way to grab it, but for now this can be marked as solved.

**Comment by ftomassetti** [comment]
Yes, I would have suggested something like this. These issues are useful for me to consider how to make the API more clear and writing documentation.

So far we focused on getting JavaSymbolSolver to work, now we are going to focus on getting a nicer api.

Thanks for your feedback!
