### ISSUE TITLE
Unable to resolve type from MethodCallExpr

### ISSUE THREAD

**Issue by tamtam22** [javaparser/javasymbolsolver#155]
**MainActivity.java**
~~~~
import android.support.v7.app.AppCompatActivity;
import org.json.JSONObject;

public class Statement extends AppCompatActivity {
    private String superSecureKey = new String(new char[]{'A', 'e', 's'});

    private class StatementTask {
        protected void onPostExecute(JSONObject jObj) {
            Encryption encryptionObj = new Encryption();
            JSONObject transaction = jObj.getJSONObject(key);

            localTransaction.insert(encryptionObj.encrypt(Statement.this.superSecureKey, transaction.getString("sender_account_number"));
        }
    }
}
~~~~
**Encryption.java**
~~~~
public String encrypt(String key, String plainText) { .... }
~~~~

I have ensured that CombinedTypeSolver has been loaded correctly with the sources folder. Although the import declaration to Encryption java class is missing, but the source folder (which contains Encryption.java) has been added to the solver already.

1) Now parsing through this MethodCallExpr node:
**`encryptionObj.encrypt(Statement.this.superSecureKey,transaction.getString("sender_account_number")`** 

Using: **`JavaParserFacade.get(AndroidAnalyzer.getCombinedTypeSolver()).solve(methodCallExpr);`**
The result is not solved.

I then tried to use **`JavaParserFacade.get(AndroidAnalyzer.getCombinedTypeSolver()).getSymbolSolver().solveMethod()`** but I do not know how to obtain the 2nd argument with List<Type> (it says type mismatch if I use getElementType() and add into List<Type>).

I also tried to obtain the type of the 2 arguments but failed to do so:

~~~~
((MethodCallExpr) node).getArguments().forEach(n -> {
    Type t = JavaParserFacade.get(AndroidAnalyzer.getCombinedTypeSolver()).getType(n);
        System.out.println(t.describe());
});
~~~~

n = **`Statement.this.superSecureKey`**
Output: **`UnsolvedSymbolException{context='unknown', name='superSecureKey', typeSolver=null}`**

n = **`transaction.getString("receiver_account_number")`**
The getString method is not solved as well when using CombinedTypeSolver with the **solve(Simplename of methodCallExpr)**.

How should I get the type based on the method names and the combinedtypesolver?

**Comment by 3ch0** [comment]
Hi

i don't know if the full error is starting with
`Issur calculating the type of the scope of MethodCallExprContext`
like issue #156, but maybe you should take a look at my answer there and try to solve method with jreOnly set to false (ReflectionTypeSolver) ?

**Comment by xdrop** [comment]
This is the same as #156
