### ISSUE TITLE
Add support for ModuleDeclaration and friends

### ISSUE THREAD

**Issue by matozoid** [javaparser/javasymbolsolver#157]
See https://github.com/javaparser/javaparser/issues/554

**Comment by matozoid** [comment]
How is this coming along? It shouldn't be hard. Want help?

**Comment by ftomassetti** [comment]
We always want help! I think we have no progress on that so far

**Comment by matozoid** [comment]
Okay, a ModuleDeclaration is a thing that can appear inside a CompilationUnit. It has a name, a module name. It may use the usual "import" statements at the top. It contains a list of module statements. Some of these contain type names that should be solvable, the rest contain module names, and I don't know if we want to solve those. If we do, this becomes much harder since module names aren't taken into consideration by JSS yet.

What's the next step?
