### ISSUE TITLE
Cannot solve primitive type

### ISSUE THREAD

**Issue by tamtam22** [javaparser/javasymbolsolver#159]
~~~~
Exception in thread "main" UnsolvedSymbolException{context='unknown', name='int', typeSolver=null}
~~~~

I would like to get the qualified name "java.lang.Integer" but unfortunately I can't do so using:
~~~~
JavaParserFacade.get(AndroidAnalyzer.combinedTypeSolver).getTypeSolver().solveType(((PrimitiveType)node).getElementType().toString()).getQualifiedName()
~~~~

**Comment by ftomassetti** [comment]
int and java.lang.Integer are not the same thing. You may want to look into com.github.javaparser.symbolsolver.model.typesystem.PrimitiveType. 

Also, you could call:
convertToUsage
`JavaParserFacade.get(AndroidAnalyzer.combinedTypeSolver).convertToUsage(node.getElementType(), node)`
and get an instance of the JSS PrimitiveType.

A TypeSolver is used to resolve reference types, while primitive types are part of the language definition, so the TypeSolver has nothing to do with them.

Does this help?

**Comment by tamtam22** [comment]
I see! Thanks for the explanation.

I have modified my code as such:
~~~~
public String getType(Node n) {
	if (.....)

	else if (node instanceof FieldAccessExpr) {
		if (((FieldAccessExpr) node).getScope().isPresent()) {
			return ((FieldAccessExpr) node).getScope().get().toString();
		}
	}

	else if (node instanceof PrimitiveType) {
		return ((PrimitiveType) node).getElementType().toString();
	}

	else if (node instanceof ArrayType) {
		return ((ArrayType) node).getElementType().toString();
	}
}
~~~~
