### ISSUE TITLE
Expose annotation usages on declarations

### ISSUE THREAD

**Issue by Minecrell** [javaparser/javasymbolsolver#161]
It would be nice if the symbol solver would provide a way to read the annotations that are defined on  a class declaration, method declaration or field declaration (and possibly all the others that apply). Since the annotation interface itself might not be present on the classpath it would be necessary to add some kind of wrapper that allows getting the declared annotation values.

For the Javassist and reflection model this should be implementable quite easily by just reading the values from the class or using reflection. In a simplified form, if all values are just literals (and no constant fields are referenced as values of an annotation), it could be also implemented for the JavaParser model. At a later point, this could be extended with a way to resolve these constant expressions.

**Comment by matozoid** [comment]
Moved to https://github.com/javaparser/javaparser/issues/1805
