### ISSUE TITLE
Resolving SymbolReference of recursive function

### ISSUE THREAD

**Issue by Meddan** [javaparser/javasymbolsolver#174]
Hi, I'm having trouble resolving the SymbolReference of a recursive function. After having parsed the code using JavaParser I traverse the parse tree. When encountering a methodcall I resolve it's symbolreference to get its declaration to continue parsing it. However if I do this on a recursive function it throws a null pointer exception when resolving the recursive call **if** it was called by another function in the class:

    public class Example {
          public int f(){
             return q(3);
          }

        public int q(int i) {
            if(i > 0){
                return i + q(i-1);
            } else {
                return i;
            }
        }
    }

If I get to q through f in this example I get a NullPointerException on `return i + q(i-1);` when doing `q` again without going through `f`.

**Comment by xdrop** [comment]
It seems to work fine for me

```
q(3) has type int
return q(3); has type PrimitiveTypeUsage{name='int'}
return i; has type PrimitiveTypeUsage{name='int'}
q(i - 1) has type int
return i + q(i - 1); has type PrimitiveTypeUsage{name='int'}
```

What version are you using?

**Comment by Meddan** [comment]
I am using 0.5.0.

The error is probably mine then, will return with more info.

**Comment by Meddan** [comment]
Managed to get it working on that example, however I now have an issue with the following:

```
class PragmaInstr {
    int placement;
    String idPragma;
    void process() {
        switch (placement) {
            case 3:
                fileChanged(idPragma);
        }
    }
    static void fileChanged( String msg) {

    }

}
```

When I try to solve using:  
`JavaParserFacade.get(combinedTypeSolver).solve(mce, false);  `
I get the exception  
`Exception in thread "main" java.lang.RuntimeException: Unable to calculate the type of a parameter of a method call. Method call: fileChanged(idPragma), Parameter: idPragma`

**Comment by Meddan** [comment]
@xdrop I forgot about this, but I no longer have the issue. My guess is that I made some mistakes when handling the parameters of the method call (adding them as children to other unrelated expressions) as that caused issues solving other method calls.
