### ISSUE TITLE
Generic Type without type parameters throws IndexOutOfBoundException

### ISSUE THREAD

**Issue by scienty** [javaparser/javasymbolsolver#18]
Great library and It is really helping me in my project.
I encountered problem with no workaround as of now and I have a solution too. If time permits I will fix and raise a pull request but In case it takes time and you have a luxury of spending time to give a quick fix, I am listing the solution here.

Problem Description:
Target Code
<code>
Map m = new HashMap();
m.put("a", "b");
</code>

Parsing Code;
<code>
javaParserFacade.getType(n); //where n is a MethodCallExpr or m.put("a", "b");
</code>

Throws IndexOutOfBoundException at location ReflectionClassDeclaration#solveMethodAsUsage#158

TypeUsage newValue = typeParameterValues.get(i); where typeParameterValues is empty list.

Possible Fix

```java
for (int i = 0; i < getTypeParameters().size(); i++) {
	                String nameToReplace = getTypeParameters().get(i).getName();
	                TypeUsage newValue = null;
	                if ( typeParameterValues.size() == getTypeParameters.size() ) {
	                	newValue = typeParameterValues.get(i);
	                } else {
	                	newValue = parameterTypes.get(i);
	                }
	                methodUsage = methodUsage.replaceNameParam(nameToReplace, newValue);
	            }

**Comment by ftomassetti** [comment]
Thank you @scienty for the kinds words and for reporting this!
I would really like to know more about your project.

For me this works with the current version from master. Perhaps I fixed this one recently. Are you using a compiled version from Maven central or the version from master? If you wish I can release a new version on Maven central

**Comment by ftomassetti** [comment]
I think this has been solved in the meantime
