### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by JKazma** [javaparser/javasymbolsolver#189]
I think I found a memory leak using the JavaParserFacade. Here's the code I used.

https://gist.github.com/JKazma/bc31d700beaf55935fd8a66467892ec4

Using the JVM Debugger Memory View plugin with intelliJ, I noticed that alot of objects were being created and never collected by the garbage collector. This does not happen if I comment out the 57th line in the code above. Below you can find a few screenshots of the Debugger output during runtime.

Also, the directory I'm using contains around 5000 java files.

Am I doing something wrong or is this indeed a memory issue?

![image](https://cloud.githubusercontent.com/assets/8633374/24520602/05713ab8-1557-11e7-9c5f-406a4666a7ab.png)

![image](https://cloud.githubusercontent.com/assets/8633374/24520626/17990090-1557-11e7-8542-27a530f56416.png)

![image](https://cloud.githubusercontent.com/assets/8633374/24520641/26ba7810-1557-11e7-82a0-3617c9992391.png)

**Comment by ftomassetti** [comment]
I was fearing this moment would arrive :D 

The way JavaSymbolSolver is designed is to calculate types on the fly given any kind of JavaParser node. Now that is all nice in theory but to have acceptable performance in practice we need all sort of caches. For cases in which the user want to parse a ton of files (5K is not exactly the typical project) we would need some mechanism to make the caches expire (like setting a max size and drop oldest elements).

There are a few separate caches here and there so it will not be trivial but it is definitely doable.

**Comment by JKazma** [comment]
@ftomasseti 
Glad I could put an end to your fear :)

No worries, I just worked around it by splitting the first level of the root's child directories into different JVM instances.

**Comment by mlangkabel** [comment]
I think I also had this issue once. That's why I added the `clearInstances` method to JavaParserFacade. I just call that one after completing every translation unit. But having an intelligent caching system would be much better!

**Comment by FRuffy** [comment]
I have also run into this problem. 
@mlangkabel When would you call clearInstances()? After solving a method successfully?

**Comment by mlangkabel** [comment]
No problem, let me explain :)I'm using the Javaparser to build an AST for some .java files.

**Comment by FRuffy** [comment]
Thank you for the explanation!

**Comment by matozoid** [comment]
See https://github.com/javaparser/javaparser/issues/1391
