### ISSUE TITLE
Cannot access package name or class name separately from type declaration

### ISSUE THREAD

**Issue by tnterdan** [javaparser/javasymbolsolver#190]
Right now, the qualified name string (`JavaParserTypeAdapter.getQualifiedName()`) separates packages and classes with `.`.
`{packageName}.{packageName}.{outerClassName}.{innerClassName}.{innerClassName}`

This doesn't let us access the namespace separately from the class name. There should be public methods such as `getPackageName()` and `getClassName()` to allow access to these separately.

We need this to represent the type of a node in a specific way for our application, so we want access to the constituent parts in order to format them the way we need.

**Comment by tnterdan** [comment]
I'm working on a PR to add `getPackageName()` and `getClassName()` to any place that also uses `getQualifiedName()`.

**Comment by ftomassetti** [comment]
Looking forward to the PR!
