### ISSUE TITLE
Enums missing constructors and interfaces

### ISSUE THREAD

**Issue by tnterdan** [javaparser/javasymbolsolver#194]
Enums may have constructors and may implement interfaces. However, `JavaParserConstructorDeclaration` only allows `ClassDeclaration` to have a constructor and `JavaParserEnumDeclaration` does not currently have an API that gives access to the list of constructors or interfaces.

**Comment by ftomassetti** [comment]
Good point

**Comment by samsieber** [comment]
+1 for this. Currently resolving method calls to enums that implement interface throws `UnsolvedSymbolException`, and I think adding this feature would fix that. (the interface I ran into this with was java.io.Serializable).

**Comment by lolpany** [comment]
+1

**Comment by steban83** [comment]
+1

**Comment by matozoid** [comment]
Come on, @ftomassetti !

**Comment by ftomassetti** [comment]
First step is to get https://github.com/javaparser/javaparser/pull/1315 into JP and wait for next release

**Comment by ftomassetti** [comment]
Wait, the PR in JP just enable us to get started solving the issue on JSS :D

**Comment by MathiasBollaert** [comment]
I tried the following workaround to get the enum's constructors: 

```
List<ResolvedConstructorDeclaration> constructors = new java.util.ArrayList<>();
List<BodyDeclaration<?>> constructorDeclarations = 
		this.enumDeclaration.getMembers().stream().filter(m -> m instanceof ConstructorDeclaration).collect(Collectors.toList());
		
for (BodyDeclaration<?> declaration: constructorDeclarations) {
	ConstructorDeclaration cd = (ConstructorDeclaration) declaration; 
	constructors.add(cd.resolve());
}
```		
That way, I am able to retrieve them, but this still doesn't work, as I got a ClassCastException in  JavaSymbolSolver on call of resolve():

```
Exception in thread "main" java.lang.ClassCastException: com.github.javaparser.ast.body.EnumDeclaration cannot be cast to com.github.javaparser.ast.body.ClassOrInterfaceDeclaration
	at com.github.javaparser.symbolsolver.JavaSymbolSolver.resolveDeclaration(JavaSymbolSolver.java:72)
	at com.github.javaparser.ast.body.ConstructorDeclaration.resolve(ConstructorDeclaration.java:240)
(...)
```
Analysing the source, this comes from the fact that EnumDeclaration is not a subclass of ClassOrInterfaceDeclaration. Maybe it should ?

Fixing #194 would then probably also require to update the logic of this method.

**Comment by matozoid** [comment]
I've moved this issue to the current project.
