### ISSUE TITLE
Is there a way to list out all the superclasses/subclasses of a class?

### ISSUE THREAD

**Issue by niharikaepuri** [javaparser/javasymbolsolver#201]
```
public static void main(String[] args) throws Exception 
	{
	inner = new DefaultMutableTreeNode("InnerClasses");
        tree1 = new JTree(inner);
	File projectDir = new File("/home/iiitb/Desktop/projects/pl/tree/GUI/one2");

	files_list = listClasses(projectDir);
	CompilationUnit cu;
	for(int i =0; i< files_list.size(); i++)
		{
    		try (FileInputStream in = new FileInputStream(files_list.get(i))) 
			{
    			cu = JavaParser.parse(in);

			List<TypeDeclaration> types = cu.getTypes();

    			ArrayList<String> parents = new ArrayList<>();		
    			for (TypeDeclaration typeDeclaration : types) 
				{

     				printTypes(typeDeclaration, parents);
				
   	 			}
			}
		}
	
 	}



 private static void printTypes(BodyDeclaration item, List<String> parents) 
	{
	if (item instanceof TypeDeclaration) 
		{
		TypeDeclaration type = (TypeDeclaration) item;
		System.out.println(type.getMembers()); 
      		s.add(getClassName(type.getName(), parents));

		// Class c = 	getClass(type.getName)
		// c.getSuperClass();		
		// type.getName().getSuperClass();
	
      		List<BodyDeclaration> members = type.getMembers();
      		List<String> cloneOfParents = new ArrayList<>(parents);
      		cloneOfParents.add(type.getName());
     		for (BodyDeclaration bodyDeclaration : members) 
			{
        		printTypes(bodyDeclaration, cloneOfParents);
      			}
    		}

  }

  private static String getClassName(String name, List<String> parents) {
    StringBuilder builder = new StringBuilder();
    for (String string : parents) {
      builder.append(string);
      builder.append(".");
    }
return builder.append(name).toString();

  }
```

**Comment by ftomassetti** [comment]
Yes, this is a typical thing you may want to do using JSS.
To do so you need to configure JavaSymbolSolver (set the type solver correctly).
Then you need to use the JavaParserFacade to convert the JavaParser TypeDeclaration in a JavaSymbolSolver type. Once you have it you just call the method `getAllAncestors`.

This works for getting the super classes, while if you want to find the subclasses you need a way to list all classes in your project and check them one by one to see if they have your class among their super classes.

**Comment by niharikaepuri** [comment]
public static void main(String[] args) throws Exception 
	{
	inner = new DefaultMutableTreeNode("InnerClasses");
        tree1 = new JTree(inner);
	ArrayList<String> files_list = new ArrayList<String>();
	File projectDir = new File("/home/iiitb/Desktop/projects/pl/tree/GUI/one2");
	files_list = listClasses(projectDir);
	CompilationUnit cu;
	try (FileInputStream in = new FileInputStream(files_list.get(0))) 
		{
                File f = new File(files_list.get(0));
               JavaParserTypeSolver symbol_solver = new JavaParserTypeSolver(f);
    		cu = JavaParser.parse(in);
		List<TypeDeclaration> ty = cu.getTypes();					
    		**for (TypeDeclaration typeDeclaration : ty) 
                     {
                     JavaParserFacade t = JavaParserFacade.get((TypeSolver)symbol_solver);
                      // I  dont know how to proceed from this
                      }**	
	   catch(Exception e)
		  {
			System.out.println(e);
		  }
   }

**Comment by niharikaepuri** [comment]
Thankyou for the reply. I am new in using javaparser. I have followed the steps you have mentioned. But I am getting runtime exceptions. 

Code is as follows:

**public static void main(String[] args) throws Exception 
	{
	ArrayList<String> files_list = new ArrayList<String>();
        File file_input = new File("/home/iiitb/test.java");
	CompilationUnit cu;
	try (FileInputStream in = new FileInputStream(file_input)  
	      {
              JavaParserTypeSolver symbol_solver = new JavaParserTypeSolver(file_input);
    		cu = JavaParser.parse(in);
		List<TypeDeclaration> ty = cu.getTypes();					
    		for (TypeDeclaration typeDeclaration : ty) 
                       {
                       Node N = (Node)typeDeclaration;
TypeDeclaration t = (TypeDeclaration) (JavaParserFacade.get((TypeSolver)symbol_solver).getType(N));

                       ReferenceTypeDeclaration t1 = (ReferenceTypeDeclaration)t;
                       for (ReferenceType ancestor : t1.getAllAncestors()) {
                               System.out.println("Ancestor " + ancestor.describe());
                                 }
			    }
         }    	
	   catch(Exception e)
		  {
			System.out.println(e);
		  }
}**

But I am getting runtime exceptions like

**Exception in thread "main" java.lang.NoClassDefFoundError: com/github/javaparser/ast/expr/SimpleName
	at inner_classes_all.main(inner_classes_all.java:95)
Caused by: java.lang.ClassNotFoundException: com.github.javaparser.ast.expr.SimpleName
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 1 more**


Where am I going wrong? Can some one let me know.
