### ISSUE TITLE
What is the command needed to execute

### ISSUE THREAD

**Issue by niharikaepuri** [javaparser/javasymbolsolver#202]
After downloading javasymbol solver. How do I run this package i.e., what is the command needed to run this project?

**Comment by matozoid** [comment]
This project is a library to use in other projects, so it is not runnable by itself. You can see some projects using this or JavaParser here: https://github.com/javaparser/javaparser/wiki/Projects-using-JavaParser

**Comment by niharikaepuri** [comment]
Okay. But my question is how to get the executable jar of symbol solver library. 
Suppose If I want to use some import statement in my project 
say, import com.github.javaparser.symbolsolver.javaparsermodel,  then I need to have the javaparsermodel.class in the path com/github/javaparser/symbolsolver/javaparsermodel.java right?
So, how can I get the executable jar of this symbol solver?

**Comment by ftomassetti** [comment]
There is no such thing as an executable jar of the JavaSymbolSolver library. It is a component you can use to build a program. That program would be executable on its own, the JSS is not.

If you want to use the JSS library in your project I strongly suggest you to look into Maven or Gradle: systems that handle dependencies and that can download JARs for you simply by specifying their name.

If you want to download the JARs manually you can search them on Maven (https://search.maven.org/#search%7Cga%7C1%7Cjava-symbol-solver). Note that you would also need to look for the dependencies used by each JAR, a boring process that is **NOT** suggested.

Out of curiosity, are you perhaps a student trying to use JSS for some assignment?

**Comment by niharikaepuri** [comment]
Yes, I am trying to use JSS as part of one of my projects.
