### ISSUE TITLE
Is there any way to get current symbol "value" by using Java Symbol Solver ?

### ISSUE THREAD

**Issue by kubisG** [javaparser/javasymbolsolver#207]
Hi, I'm wondering If there is a way how to get current symbol value (not just a type) by JavaSymbolSolver.

I have a following test (important parts are bold) and I need to know the current value of baseUrl symbol in driver.get(...) method call. 

public class ZezulaTest {
    private WebDriver driver;
    **private String baseUrl;**
    private boolean acceptNextAlert = true;

    @Before
    public void setUp() throws Exception {
        driver = new FirefoxDriver();
        **baseUrl = "http://www.snowboard-zezula.cz/";**
        driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
    }

    @Test
    public void testZezula() throws Exception {
        **driver.get(baseUrl + "snowboard-shop-brno");**
        driver.findElement(new By.ById("45"));
        driver.findElement(By.id("productbox-63065-image")).click();
        new Select(driver.findElement(By.id("product-size-select"))).selectByVisibleText("M, skladem");
        driver.findElement(By.id("frmcartAddForm-add")).click();
    }
}

Thanks a lot for the answer.

**Comment by ftomassetti** [comment]
No. That would be theoretically possible only in some cases, when the value would be statically evaluatable and not depending on external values (user inputs, db, etc). This is not a feature of JavaSymbolSolver. It would require a significant amount of work and it could be interesting to do that in a separate project. If someone would be interested in such project I could help
