### ISSUE TITLE
Javaparser Symbol solver vs JDT, how is it going?

### ISSUE THREAD

**Issue by sergiofigueras** [javaparser/javasymbolsolver#211]
Hello guys,

We've a huge code generator project that current makes use of JDT analysis elements to generate the code. But, as anyone that worked with JDT before, knows how tricky is to work with it, and how its design is old and hard to manage.

My question is: can anybody provide me an idea about how close Javaparser Symbol solver is close to results of JDT? For instance, does it analyzes statements like "this.x = x" as a field assignment, an assignment expression, and a simple name variable? Does java parser symbol analyzer have such capability of analyzing in that level of detail?

Thanks,

Sergio.

**Comment by ftomassetti** [comment]
Hi Sergio,
yes the idea was to build something to replace the JDT but making it as easy as possible to use. With simple dependencies (no OSGI) and to configure (you basically need to list the jars and the source directory to consider).

JSS is not as mature as JDT so it is correct 99% of the time (it is used in commercial projects) but it could give slightly incorrect answers when generics and lambdas interact in complex ways.

That said the idea is that you use it to complement JavaParser. You pick nodes in the AST that represent references and ask JSS to figure out that thing to what is referring to. It will return the corresponding declaration.

You would:
1. take your code and call JavaParser, it will give you an AST
2. take a node of the AST representing a name for example and call JavaParserFacade.solve. You would get back a [ValueDeclaration](http://static.javadoc.io/com.github.javaparser/java-symbol-solver-model/0.5.3/com/github/javaparser/symbolsolver/model/declarations/ValueDeclaration.html). 

Once you have the ValueDeclaration you could check if it is a field or a parameter for example. Suppose the name is a reference to a parameter, you could either call `myValueDeclaration.asParameter()` or cast it to `ParameterDeclaration`. Once you have a Parameter Declaration you can check the type of the parameter, if it is variadic, to which method it belongs, etc.

You have all these interfaces like ParameterDeclaration, FieldDeclaration etc which could represents declarations coming from the JDK, from JAR files or from source code but they are all exposed with the same interface.

Or you can give it an expression and it will figure it how the type (like "String" or "Map<A, ? extends String", or whatever else).

I hope does it help, if not feel free to ask as many questions as you want. We would be also happy to know more about your project.
