### ISSUE TITLE
Anonymous classes are not considered a valid resolution context

### ISSUE THREAD

**Issue by staslev** [javaparser/javasymbolsolver#226]
Consider the following snippets:

```java
public abstract class DoFn<I, O> {

    public abstract class Context {...}
    public abstract class ProcessContext extends Context { ... }

}
```

```java
ParDo.of(new DoFn<Long, Long>() {
            @Override
            public void processElement(ProcessContext c) {
            }
          })

```

Since `ProcessContext` is an inner class, it needs to be resolved in the context of the anonymous class `new DoFn() {...}`, however this is currently unsupported in `JavaParserFactory.getContext(...)` since it does not handle the case of `node instanceof ObjectCreationExpr`.

Consequently, instead of eventually trying to resolve `DoFn.ProcessContext`, the flow tries to resolve only the direct name -  `ProcessContext`, and thus fails.

This is actually a tricky one, and I have not been able to come up with a good way to handle this.
@ftomassetti any words of wisdom?

**Comment by ftomassetti** [comment]
I can confirm that it is a tricky one :D 
We should create a new context to support this case.

**Comment by staslev** [comment]
I'll try to tackle this.
