### ISSUE TITLE
Problem accessing "length" field of an Array type object within lambda

### ISSUE THREAD

**Issue by RaulGracia** [javaparser/javasymbolsolver#234]
HI all,

I found a problem with JSS trying to infer the type of a lambda in which I access to the "length" field of an Array variable. Here is the code:

```
Stream<String> distFile = Stream.of("aa", "bb");
distFile.map(s -> s.split(" ").length).reduce((a, b) -> a + b);
```

When I execute this, JSS throws the following error (full trace at the end of this message):

> java.lang.NoSuchMethodError: com.github.javaparser.ast.expr.FieldAccessExpr.getScope()Ljava/util/Optional;
> 	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:180)

If we change the second line of this example as follows:
`distFile.map(s -> Arrays.asList(s.split(" ")).size()).reduce((a, b) -> a + b);`

It works. I hope this helps on focusing the problem and its scope.

Thanks a lot,
Raúl.

> java.lang.NoSuchMethodError: com.github.javaparser.ast.expr.FieldAccessExpr.getScope()Ljava/util/Optional;
> 	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:180)
> 	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:39)
> 	at com.github.javaparser.ast.expr.FieldAccessExpr.accept(FieldAccessExpr.java:81)
> 	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getTypeConcrete(JavaParserFacade.java:394)
> 	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:286)
> 	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:280)
> 	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:423)
> 	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:39)
> 	at com.github.javaparser.ast.expr.LambdaExpr.accept(LambdaExpr.java:123)
> 	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getTypeConcrete(JavaParserFacade.java:394)
> 	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:286)
> 	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:280)
> 	at main.java.analyzer.visitor.StatementsExtractor.getLambdaTypeFromNode(StatementsExtractor.java:123)
> 	at main.java.analyzer.visitor.StatementsExtractor.visit(StatementsExtractor.java:99)
> 	at com.github.javaparser.ast.expr.MethodCallExpr.accept(MethodCallExpr.java:103)
> 	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:289)
> 	at com.github.javaparser.ast.stmt.ExpressionStmt.accept(ExpressionStmt.java:71)
> 	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.lambda$visit$17(VoidVisitorAdapter.java:116)
> 	at java.util.ArrayList.forEach(ArrayList.java:1249)
> 	at com.github.javaparser.ast.NodeList.forEach(NodeList.java:208)
> 	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:116)
> 	at com.github.javaparser.ast.stmt.BlockStmt.accept(BlockStmt.java:72)
> 	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.lambda$visit$100(VoidVisitorAdapter.java:414)
> 	at java.util.Optional.ifPresent(Optional.java:159)
> 	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:414)
> 	at com.github.javaparser.ast.body.MethodDeclaration.accept(MethodDeclaration.java:107)
> 	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.lambda$visit$29(VoidVisitorAdapter.java:168)
> 	at java.util.ArrayList.forEach(ArrayList.java:1249)
> 	at com.github.javaparser.ast.NodeList.forEach(NodeList.java:208)
> 	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:168)
> 	at com.github.javaparser.ast.body.ClassOrInterfaceDeclaration.accept(ClassOrInterfaceDeclaration.java:97)
> 	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.lambda$visit$40(VoidVisitorAdapter.java:190)
> 	at java.util.ArrayList.forEach(ArrayList.java:1249)
> 	at com.github.javaparser.ast.NodeList.forEach(NodeList.java:208)
> 	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:190)
> 	at main.java.analyzer.JavaStreamsJobAnalyzer.analyze(JavaStreamsJobAnalyzer.java:97)
> 	at main.java.analyzer.SparkJavaJobAnalyzer.analyze(SparkJavaJobAnalyzer.java:104)
> 	at test.java.cases.SparkSimpleTextAnalysisTest2.testJob(SparkSimpleTextAnalysisTest2.java:22)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at junit.framework.TestCase.runTest(TestCase.java:176)
> 	at junit.framework.TestCase.runBare(TestCase.java:141)
> 	at junit.framework.TestResult$1.protect(TestResult.java:122)
> 	at junit.framework.TestResult.runProtected(TestResult.java:142)
> 	at junit.framework.TestResult.run(TestResult.java:125)
> 	at junit.framework.TestCase.run(TestCase.java:129)
> 	at junit.framework.TestSuite.runTest(TestSuite.java:252)
> 	at junit.framework.TestSuite.run(TestSuite.java:247)
> 	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
> 	at org.junit.runners.Suite.runChild(Suite.java:128)
> 	at org.junit.runners.Suite.runChild(Suite.java:27)
> 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
> 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
> 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
> 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
> 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
> 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
> 	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
> 	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
> 	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
> 	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
> 	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
> 	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

**Comment by matozoid** [comment]
This is caused by an incorrect combination of JavaParser and JavaSymbolSolver. Either @ftomassetti did something strange with the release, or you have mismatched libraries on your classpath. Can you tell us the versions?

**Comment by ftomassetti** [comment]
Note that you should **not** add javaparser as a dependency because it is already a dependency of JSS

**Comment by RaulGracia** [comment]
You are right, this was the cause of the problem. In the pom.xml of my application I had as dependencies both JavaParser and JavaSymbolSolver. I removed JavaParser from the dependency list and now the test passes.

Thanks a lot!
Raúl.
