### ISSUE TITLE
Inner types are not accessible from inherited types

### ISSUE THREAD

**Issue by Gottox** [javaparser/javasymbolsolver#237]
Take this example:
```java
class A {
    class InnerA {
    }
}

class B extends A {
    InnerA field;
}
```

For the java compiler ```InnerA``` is accessible from ```class B```. jss fails to discover this class though.

As always, I'm preparing a PR with a test for this issue. 😃

**Comment by Gottox** [comment]
give me a sec, this code doesn't trigger my issue. Let me investigate.

**Comment by Gottox** [comment]
okay, I used an outdated jar, my mistake

**Comment by ftomassetti** [comment]
It happens even to the best ones :)
