### ISSUE TITLE
Knowing where an argument is from ?

### ISSUE THREAD

**Issue by lodart** [javaparser/javasymbolsolver#250]
Hello,
I have a question : is there a way, with JSS, to know where an argument is from ? For example :
```java
...
public void method(...){
    ...
    connect(u);
}
```
Was `u` declared in the method body ? Does it come from its parameters ? Is it a static class attribute ? ...

Thank you !

**Comment by ftomassetti** [comment]
When you use `JavaParserFacade.solve` you should get back an instance of `SymbolReference<? extends ValueDeclaration>`.

A [ValueDeclaration](http://static.javadoc.io/com.github.javaparser/java-symbol-solver-model/0.5.3/com/github/javaparser/symbolsolver/model/declarations/ValueDeclaration.html) has many methods that can be used to figure out what kind of value it is.  For example, you can call `isParameter` to check if it is a parameter and in that case you can call `asParameter` on that value converting it to a parameter declaration on which you can call more specific methods.

Does it help?

**Comment by lodart** [comment]
This is exactly what I wanted ! Thank you so much :)

**Comment by lodart** [comment]
Hum, I still struggle a bit : can I get the wrapped node with this method ? `valueDeclaration.asParameter()` gives me a `ParameterDeclaration`, and not a `JavaParserMethodDeclaration` and I can't do : `JavaParserParameterDeclaration jppd = argDeclaration.asParameter();`

**Comment by ftomassetti** [comment]
Oh, I see, we do now have the asParameter method implemented correctly. I should fix that

**Comment by ftomassetti** [comment]
This should be fixed by #254 and be included in next release
