### ISSUE TITLE
IsAssignableBy fails if TypeParameters have different names

### ISSUE THREAD

**Issue by mlangkabel** [javaparser/javasymbolsolver#251]
Please consider the following code snippet:

```java
package java_sample;

class Test {
	
	class Foo { }
	
	interface GenericBase <F> { }
	
	class GenericDerived <F extends Foo> implements GenericBase<F> { }

	private <B extends Foo> void foo(GenericBase<B> g) { }
	
	private <D extends Foo> void foo(GenericDerived<D> g) { }
	
	void bar() {
		GenericDerived<Foo> sl = new GenericDerived<>();
		foo(sl);
	}
}
```

When trying to solve the method call of `foo` inside tbe method `bar` I'm running into a MethodAmbiguityException. This is caused by the parameters of both `foo` methods not being assignable to each other according to the `ReferenceType.isAssignableBy` method. If I change the name of `D` to `B` everything works out well.

**Comment by mlangkabel** [comment]
Pull request #252 will fix this issue, The type parameter checks I added for comparing ReferenceTypes may still be missing some cases but I guess that we can fix them one at a time :)

**Comment by ftomassetti** [comment]
It should be now fixed
