### ISSUE TITLE
Find dependencies

### ISSUE THREAD

**Issue by serdaoezuen** [javaparser/javasymbolsolver#258]
Hello,
after reading quite a bit about javaparser and also trying a few things out, I am still not sure if the following is possible:

ClassA {
}

ClassB{
 ClassA.foo();
}

Basically I want to know if ClassB is using ClassA or any other class for that matter.
What I could do is check for the String classA.name inside classB, but I wouldnt need javaparser for that anyway(regex & BufferedReader are sufficient) + it is really inaccurate in some scenarios.

Can I check for class usage in other classes using the actual objects to be 100% sure of usage?

Thanks for any clarification

**Comment by ftomassetti** [comment]
I would really, really, really suggest not using regex for something like this.

What you want to do is resolve all the value and method references in class B and figure out if they refer to symbols in ClassA. Once you have the symbol and method declaration you can easily see to which class they refer.

What you want to do is to use the class JavaParserFacade and its solve* methods

**Comment by serdaoezuen** [comment]
Thanks for the super fast response! I'll read into the JavaParserFacade

**Comment by serdaoezuen** [comment]
As a follow-up question: Is there any way to make JavaParserTypeSolver work with the base directory of a project rather than the src directory (Is there any point from your side to not make it work with the baseDir)? All I have access on is the base directory and the current file that I am analyzing.

**Comment by ftomassetti** [comment]
well, I do not think this would make sense to change JSS with this feature. You can probably calculate the root directory of the source code by looking for Java files.

Out of curiosity: for which reason are you using JSS?

**Comment by serdaoezuen** [comment]
I am developing a plugin for SonarQube which calculates metrics including couplings, LCOM and others. Using JP/JSS for precision as I'd like to get as close as possible to 100% correctness

**Comment by ftomassetti** [comment]
That sounds as a really interesting project! I would love to get updates and learning more about it

**Comment by serdaoezuen** [comment]
Unfortunately, I'll have to bother you again. I've come across an issue with static methods.

Let's say in class foo is a static method called bar. So you dont have to use the new operator to access that method in another class.

```
public class test{
   foo.bar();
}
```

The return type of bar is easy accessible with MethodCallExpr and to my understanding (and trying out a lot of things) NameExpr should be used to find the origin of foo, however I'm getting an exception 

```
Exception in thread "main" UnsolvedSymbolException{context='Solving Bar', name='Bar', typeSolver=null}

//tempFile points to src directory of the package in which foo and test are in
CombinedTypeSolver combinedTypeSolver = new CombinedTypeSolver();
combinedTypeSolver.add(new ReflectionTypeSolver());
combinedTypeSolver.add(new JavaParserTypeSolver(tempFile));

List<NameExpr> nameExprs = Navigator.findAllNodesOfGivenClass(cu, NameExpr.class);

	for (NameExpr ne : nameExprs) {
	System.out.println( JavaParserFacade.get(combinedTypeSolver).getType(ne).asReferenceType().getQualifiedName());
		}

```

I've solved pretty much all things I've wanted to, except for these static calls. Is this a bug, or should I be using something else than NameExpr?

**Comment by ftomassetti** [comment]
No problem, we are happy to help and questions help us improving JSS. However if this is a different issue it would make things easier for us if you could open separate tickets. Feel free to open as many as you need.

Could you please provide the complext example you are using?
In this case I do not see where `foo` would be coming from.

**Comment by serdaoezuen** [comment]
Thanks! I felt that this was still kind of around the same issue, so I did not open a new one.

Imagine you have 2 classes Test and Foo which are in the same package.
```

public class Test {
  Foo foo = Foo.bar();
}

public class Foo{
        static Foo foo = new Foo();

	public static Foo getInstance() {
		return foo;
	}
}
```

How would you go about resolving, where the method call Foo.bar() is coming from (as in which class)? In this case it's just coincidence that MethodCallExpr would return Foo and thus the result, but there are a lot of cases, for instance in method calls where you do something like 


```
foo(Foo.method());

//or something like this, just like you use for example in your Navigator. 
//How do you resolve Navigator and Expression? 
Navigator.findAllNodesOfGivenClass( node, Expression.class)


```

I'm trying to resolve Foo rather than the method call, but haven't found a way to deal with these static method calls yet, as NameExpr doesnt work for me. 

I hope it's somewhat understandable

**Comment by serdaoezuen** [comment]
After doing a temporary solution with Expression and String I have found a solution.

Simply use MethodCallExpr and the corresponding JavaParserFacade method.

```
//something like this depending on what you want to do
if (JavaParserFacade.get(combinedTypeSolver).solve(md).getCorrespondingDeclaration().isStatic()) {
JavaParserFacade.get(combinedTypeSolver).solve(md)
						.getCorrespondingDeclaration().getClassName()
}
```

My fault was getting the Arguments of MethodCallExpr and then using the getType().asReferenceType().getQualifiedName() chain of JavaParserFacade which is not able to solve these static methods
