### ISSUE TITLE
[Question] Solve types in multicatch.

### ISSUE THREAD

**Issue by hugofmelo** [javaparser/javasymbolsolver#259]
Hi JP devs, Im trying to resolve the types in a multicatch, but Im getting a UnsupportedOperationException. Example:

```
// Solving "regular" catch clause
if ( catchClause.getParameter().getType() instanceof ClassOrInterfaceType)
{
	// ReferenceType here is com.github.javaparser.symbolsolver.model.typesystem.ReferenceType
	ReferenceType refType = (ReferenceType) facade.getType(catchClause.getParameter());
}
// Solving multicatch
else if (catchClause.getParameter().getType() instanceof UnionType)
{
	UnionType multiCatch = (UnionType) catchClause.getParameter().getType();
	Iterator<com.github.javaparser.ast.type.ReferenceType> i = multiCatch.getElements().iterator();
	while ( i.hasNext() )
	{
                // Got an UnsupportedOperationException
		ReferenceType refType = (ReferenceType) facade.getType(i.next());
	}
}
```

What can I do?

**Comment by ftomassetti** [comment]
It could be worth sharing more details, like for example the text of the exception. It is probably a bug (i.e., something we need to still implement)

**Comment by hugofmelo** [comment]
Hi @ftomassetti,

maybe we can simplify the question to: "how to solve a ClassOrInterfaceType?". Is this possible?

Because on resolving regular catch clauses, I call facade.getType (Parameter). I can't do this to a multicatch clause.

**Comment by ftomassetti** [comment]
It is probably not very intuitive but you can solve a JP Type using this method: http://static.javadoc.io/com.github.javaparser/java-symbol-solver-core/0.5.5/com/github/javaparser/symbolsolver/javaparsermodel/JavaParserFacade.html#convertToUsage-com.github.javaparser.ast.type.Type-

**Comment by hugofmelo** [comment]
Works nicely. Thank you!

**Comment by ftomassetti** [comment]
Question answered, closing
