### ISSUE TITLE
How to get original referenced AST node using JSS?

### ISSUE THREAD

**Issue by chenershuile** [javaparser/javasymbolsolver#261]
I'm intending to build a web-side java code viewer to store and index all code which belong to different project. 
I think may be such a project should work like this:
1. Gather all the source code. They may comes from source.jar which hold in central maven repository.
2. Build the AST nodes separately in different .java file.
3. Using JSS to calculate the references since we need to **jump to the symbol declaration as common IDE does**.

I have found that java-parser can generate AST node for each .java file. In the meantime , java-parser can also holds the token stream info like the start index and end index. Such an AST node information is quit useful since we need this to format the origin file into a highlight mode.
After that, we need to walk through the Syntax tree and for every node which is  reference-able, we need JSS to tell us which AST node it declared in.
For example:
in Person.java 
`class Person {`
`   Name name;`
` }`
in Name.java
`class Name {
String firstName;
String secondName;
}`
In the view of Person.java page (remember we are build a code viewer, so we need to manipulate and demonstrate the Person.java in html), when user need to jump to `Name`, we need to know exactly which  AST node such a symbol is reference to. In the above case, we need to get the `Name` Class AST node  which is in Name.java file.

Is JSS capable to do this?  I know how to use JSS to solve the type of node, but I don't know how to fetch or point user to the origin declaration AST node in another file.
Am i missing something in the guide or the example ?

**Comment by ftomassetti** [comment]
Yes, JSS can do that. When you resolve `Name` you will get a `TypeDeclaration`. Let's suppose it is a `ClassDeclaration`. Depending on where it comes from it could a JarClassDeclaration, a ReflectionClassDeclaration os a JavaParserClassDeclaration. In the latter case you can call `getWrappedNode` and get the JavaParser AST node, which knows the position in the source code of the declaration itself. Hope it helps.

**Comment by chenershuile** [comment]
It works, Thanks a lot !

**Comment by ftomassetti** [comment]
You are welcome. Let us know about your website
