### ISSUE TITLE
How to find the begin line and paramters's full name in some method simply？

### ISSUE THREAD

**Issue by CoolAcsi** [javaparser/javasymbolsolver#262]
Hi,
I want to reslove the mapping about that one method call another method，and get these methods‘s begin line ,package name ,class name and so on...

Can I do it simply? As a matter of fact, I haven't found a solution yet.

If you wrap a javaparser.MethodDeclaration in javasymbolsolver.MethodDeclaration? I think it will be very convenient to do something.

**Comment by ftomassetti** [comment]
Yes, you can.

You can use the symbol solver to find the MethodDeclaration corresponding to a method call. Once you have that you can find all the information you need (package name, class name, line, etc).

For details I suggest you get a look on the chapter on JavaSymbolSolver of [this book](https://leanpub.com/javaparservisited) (available for free) and then if you have question feel free to ask here or using the [gitter channel](https://gitter.im/javaparser/javaparser).

**Comment by CoolAcsi** [comment]
@ftomassetti  thanks for your answer.And I'm sorry, my English is very poor...
I have read this book in javaparservisited,and I know how to  find the MethodDeclaration corresponding to a method call. But javaSymbolSolver.MethodDeclaration's methods is very little and I can't find what I need...

Another question is, if i just use JavaParserTypeSolver, i will be not able to find the MethodDeclaration which is in this directory corresponding to a method call,But you can find it if i work with ReflectionTypeSolver at the same time. I dont know why i happen...  Did I get it wrong?

**Comment by ftomassetti** [comment]
Which questions you cannot answer once you get the JSS MethodDeclaration?

The JavaDoc for that class is [here](http://static.javadoc.io/com.github.javaparser/java-symbol-solver-model/0.5.6/com/github/javaparser/symbolsolver/model/declarations/MethodDeclaration.html).

- you cannot find the begin line for all the method declarations, only for the ones coming from source code. If you MethodDeclaration is an instance of [JavaParserMethodDeclaration](http://static.javadoc.io/com.github.javaparser/java-symbol-solver-core/0.5.6/com/github/javaparser/symbolsolver/javaparsermodel/declarations/JavaParserMethodDeclaration.html) you can cast to that type and then find the begin line from there
- to find the package name call [declaringType](http://static.javadoc.io/com.github.javaparser/java-symbol-solver-model/0.5.6/com/github/javaparser/symbolsolver/model/declarations/MethodLikeDeclaration.html#declaringType--) then on the result call [getPackageName](http://static.javadoc.io/com.github.javaparser/java-symbol-solver-model/0.5.6/com/github/javaparser/symbolsolver/model/declarations/TypeDeclaration.html#getPackageName--)
- to find the class name call [declaringType](http://static.javadoc.io/com.github.javaparser/java-symbol-solver-model/0.5.6/com/github/javaparser/symbolsolver/model/declarations/MethodLikeDeclaration.html#declaringType--) then on the result call [getClassName](http://static.javadoc.io/com.github.javaparser/java-symbol-solver-model/0.5.6/com/github/javaparser/symbolsolver/model/declarations/TypeDeclaration.html#getClassName--)

Does it help?

Regarding the second question I am not sure I understand, I would need more details and I suggest you open a different issue for that.

**Comment by CoolAcsi** [comment]
Thank you ,It helps me a lot~

**Comment by ftomassetti** [comment]
I think we answered it. Please reopen it if it is unclear.

**Comment by davideuler** [comment]
For JavaParserMethodDeclaration, call  this line to get begin line number:
javaParserMethodDeclaration.getWrappedNode().getRange().get().begin
