### ISSUE TITLE
Can not find MethodDeclaration by JavaParserTypeSolver

### ISSUE THREAD

**Issue by CoolAcsi** [javaparser/javasymbolsolver#263]
I already know what to do by this issue #258 ,thanks (●'◡'●)

---------- Original Question ----------
Hi ,
I want to find MethodDeclarations corresponding MethodCallExps in a source file.And I just do what as the book.

```
TypeSolver solver =  new JavaParserTypeSolver(new File(the_project_home));
List<MethodCallExpr> methodCalls = Navigator.findAllNodesOfGivenClass(cu, MethodCallExpr.class);
methodCalls.forEach(callExpr->{
    try {
        MethodDeclaration methodSymbolDeclaration = (MethodDeclaration) JavaParserFacade.get(solver).solve(callExpr).getCorrespondingDeclaration();
    } catch (RuntimeException e){
        LOGGER.debug("method declaration not found",e);
    }
});
```
But in this way,I can not get any MethodDeclaration in specified directory..

Did I do something wrong?

**Comment by ftomassetti** [comment]
Good! SHould I close the ticket, then?

**Comment by CoolAcsi** [comment]
Of cource~
