### ISSUE TITLE
Get declaring type/method/constructor of JavassistTypeParameter

### ISSUE THREAD

**Issue by mlangkabel** [javaparser/javasymbolsolver#264]
Currently the `JavassistTypeParameter` just provides a method to get the name of the `qualifier` which is not enough information for my current use case. I'd like to extend the stored information to enable the JavassistTypeParameter to return something bigger. Maybe a `TypeParameterizable`.

**Comment by ftomassetti** [comment]
Which information do you need that you cannot get?

**Comment by mlangkabel** [comment]
We need to get the method/constructor parameters and the other type parameters of the context of the type parameter

**Comment by ftomassetti** [comment]
Right, make sense. Thanks for clarifying

**Comment by mlangkabel** [comment]
Implemented with merge of pullrequest #266 (thanks @ftomassetti for merging).

**Comment by ftomassetti** [comment]
Thanks for writing the PR!
