### ISSUE TITLE
Can I find a MethodDeclaration corresponding to javaparser.MethodDeclaration?

### ISSUE THREAD

**Issue by CoolAcsi** [javaparser/javasymbolsolver#265]
Hello,
I have a MethodDeclaration from AST，And I want get MethodDeclaration corresponding to it.
Can i do it ?

**Comment by ftomassetti** [comment]
Look in [JavaParserFacade](http://static.javadoc.io/com.github.javaparser/java-symbol-solver-core/0.5.6/com/github/javaparser/symbolsolver/javaparsermodel/JavaParserFacade.html) for the method named solve that takes a `com.github.javaparser.ast.expr.MethodCallExpr methodCallExpr`.

Also, take a look to [this book](https://leanpub.com/javaparservisited), in particular to the chapter on the JavaSymbolSolver.

Hope it helps

**Comment by CoolAcsi** [comment]
I have no MethodCallExpr but `com.github.javaparser.ast.body.MethodDeclaration`，now I want to resolve `com.github.javaparser.symbolsolver.model.declarations.MethodDeclaration` corresponding to `com.github.javaparser.ast.body.MethodDeclaration`.
Can i do it?

**Comment by ftomassetti** [comment]
If you know already the JavaParser MethodDeclaration then you can simply instantiate com.github.javaparser.symbolsolver.javaparsermodel.declarations.JavaParserMethodDeclaration which implements com.github.javaparser.symbolsolver.model.declarations.MethodDeclaration. There is no resolution to do.

**Comment by CoolAcsi** [comment]
Oh,I see.
Thank you~

**Comment by ftomassetti** [comment]
You are welcome
