### ISSUE TITLE
Test solving symbols in Javasymbolsolver code base

### ISSUE THREAD

**Issue by mlangkabel** [javaparser/javasymbolsolver#280]
Right now we already have tests that use the javaparser source code and make sure that all symbols in that code base can be solved. I think it would be a great idea to take a snapshot of the JSS and set up equivalent tests for that code base.

As the JSS code references javaparser quite a lot we could use a JarTypeSolver for solving those external symbols to test that functionality as well.

While working on Sourcetrail I gave it a shot and tried to solve symbols in the JSS codebase but I'm still getting 668 references (mostly methods calls) that could not be solved. So that's why I think setting up these tests would be a great idea!

**Comment by mlangkabel** [comment]
I have set up those tests. We are getting 131 times an ERROR and 131 times an UNSOLVED output. I think I'll commit them so that we can start on fixing those cases!

**Comment by ftomassetti** [comment]
Fixed by #282
