### ISSUE TITLE
clean project dependencies

### ISSUE THREAD

**Issue by mlangkabel** [javaparser/javasymbolsolver#281]
* model and core projects reference junit and easymock dependencies even though these projects do not define any tests
* different javaslang version referenced in core, logic and model
* only the model references javaparser (is that correct?)

**Comment by ftomassetti** [comment]
1. You are right
2. To be fixed
3. I think the dependencies are inherited. Other modules depends on model and therefore they depends indirectly on JP

**Comment by mlangkabel** [comment]
fixed with merge of pull request #286
