### ISSUE TITLE
Improve CPU usage of JavaParserTypeSolver

### ISSUE THREAD

**Issue by mlangkabel** [javaparser/javasymbolsolver#290]
After profiling CPU usage of the JavaParserTypeSolver it turns out that most of the time (around 60% for my test project) is spent inside the `parse` method. To be even more precise: Most of the time is spent trying to acccess files that don't exist because the type the JavaParserTypeSolver is looking for is actually defined inside another type inside another file.

**Comment by mlangkabel** [comment]
The fact that a file does not exist is actually valuable information that we shouldn't just throw away. So I will try to extend the caching inside the JavaParserTypeSolver to keep track of this information.

**Comment by mlangkabel** [comment]
Looking good! The commit fa01fa03b4d782e23ce8196df2e3a135b271c68a also cut the time for the tests in half :)

**Comment by ftomassetti** [comment]
Wow!! Thank you, this is quite an achievement!
Really appreciated!

P.S. on my side I am looking into #9 ...

**Comment by mlangkabel** [comment]
Done by merging pull request #291
