### ISSUE TITLE
[Question] Finding out a method is overrided or not

### ISSUE THREAD

**Issue by cemuyarhub** [javaparser/javasymbolsolver#296]
Hello dear developers, 
I have a question about JavaParser. Do you know a way that; I can know if a method declaration is an Override or not?
 I am trying to find out roots of each method declarations(Is the method is overriden? If it is overriden then where is the original source of declaration?) in my java files by using your java parsing libraries(JavaParser, SymbolSolver) for my school project. I have used several forms of method "visit", one of them is in the example below:
   `      @Override
        public void visit(MethodDeclaration n, Void arg) {
            /* here you can access the attributes of the method.
             this method will be called for all methods in this 
             CompilationUnit, including inner class methods */
          //  System.out.println(n.getName());
        	tempList.add(n.getName().toString());

            super.visit(n, arg);
        }    `

I have also read the Guide Book but I couldn't get the answer. As far as I could get is only method names. 
Thank you in advance.

**Comment by ftomassetti** [comment]
Currently there is not an easy way to do so. We use a trick in method resolution logic, by ordering the methods from the most specific class to the more general ancestor we always get the right version of it but we should add a method to answer this question directly.

**Comment by cemuyarhub** [comment]
Thank you for your response. I understand your solution but i couldn't find the implementation way for ordering the methods. If you can help me about this i would be really happy. 
Thanks in advance :)

**Comment by matozoid** [comment]
Moved
