### ISSUE TITLE
[Question] find all strings where variable used

### ISSUE THREAD

**Issue by daniilkartashev** [javaparser/javasymbolsolver#297]
Hello! I have a question:
With SymbolSolver, can i find all strings where the specific variable is used?

====
Great project btw :)

**Comment by ftomassetti** [comment]
Thanks!
I am not sure what you mean. Do you mean things like:

`"foo " + myVar` ?

**Comment by daniilkartashev** [comment]
My english isn't great :)
I mean, i have variable declaration, for example:

DataObject DO = ...;

and i want to find java code where this DO was used
for example

somefunction(DO);
DO.toString();

**Comment by daniilkartashev** [comment]
Hmm, maybe proper way to say it - want to find all expressions where variable was used

**Comment by ftomassetti** [comment]
oh, ok. Well, you can fine all NameExpr and then call JavaParserFacade.solve(myNameExpr). It should find the corresponding declaration and you can then check if it is your VariableDeclaration or not.

**Comment by daniilkartashev** [comment]
Thank you very much!

**Comment by ftomassetti** [comment]
You are welcome!
