### ISSUE TITLE
Compatible with javaparser Java 9.0?

### ISSUE THREAD

**Issue by un0btanium** [javaparser/javasymbolsolver#320]
Hello,

i just recently stumbled upon your javaparser for Java 9.0 and wondered if/when the javasymbolsolver will be compatible with a javaparser version that supports parsing Java 9.0.

Currently javasymbolsolver 0.6.0 depends on javaparser 3.3.0, but i am not sure since which version of javaparser Java 9.0 is supported.

**Therefore, my question is: Does JSS 0.6.0 already support Java 9.0 parsing? If not, when is it to be expected to be available?**

Thanks you :)

**Comment by un0btanium** [comment]
Alright, cool. Thank you for your fast response 👍

You might want to state that in your Readme. You stated Java 8 features under "State of the project", which confused me a bit. I would wish a quick statement about the early Java 9 support.

**Comment by matozoid** [comment]
@ftomassetti - maybe you can give some priority to https://github.com/javaparser/javasymbolsolver/issues?q=is%3Aissue+is%3Aopen+label%3Ajava9
