### ISSUE TITLE
Javassist*Declarations should use typesolver to get to their superclass/interfaces instead of relying on the internal ctClass.classPool, as that has too limited a view on the classpath

### ISSUE THREAD

**Issue by WimTibackx** [javaparser/javasymbolsolver#326]
_This issue was first discussed via the JavaParser gitter. The description below is a recap of that discussion._

**Description**
When solving symbols, the Javassist*Declaration classes will check their superclass and their interfaces. However, they use their internal CtClass instance to get to these declarations. The way we construct the CtClass in JavassistFactory, it only has their own jar + system level stuff (java.lang.Object etc) on the classpath. Thus if the interface or superclass is in another jar, it won't be able to find it.

**Theoretical example**
Consider the following case: I have a jar called A.jar and a jar called B.jar. B.jar contains public interface FooInterface, and A.jar contains public class FooImplementation implements FooInterface. I'm using a CombinedTypeSolver with a JarTypeSolver for B, a JarTypeSolver for A, and a ReflectionTypeSolver.
Via `TypeSolver::solveType("<pkg>.FooImplementation")` I get a `JavassistClassDeclaration`. That classDeclaration was constructed using the classpool containing only A.jar. Thus, if I try to access anything on the interface, Javassist fails to find the interface, as it is not in the classpool.

Consider also this example: what if I have a CombinedTypeSolver with a JarTypeSolver, a JavaParserTypeSolver, and a ReflectionTypeSolver. If I have the situation outlined above, but with FooInterface in the JavaParserTypeSolver, I'm guessing that should also work (and thus: classes in the JavaParserTypeSolver should maybe also be somehow included in that classpath)?

**Solution**
The Javassist*Declaration should just get the FQN of its superclass/interfaces, and use TypeSolver to get to the declaration instead of using CtClass to do that.

**Further considerations**
Javassist*Declaration classes should also be checked for other uses of CtClass where this might cause issues.

**Practical testcases**
I have some failing ignored tests for #322, which I'll tag with this issue. These are in `SymbolSolverWithJavassistEnumTest` and `SymbolSolverWithJavassistClassTest`. I'll update this issue with a link to the PR as soon as there is a PR.

**Comment by matozoid** [comment]
Moved this to the new project location.
