### ISSUE TITLE
Symbol solver: continue iterating over the AST after an exception has been caught

### ISSUE THREAD

**Issue by Cale-92** [javaparser/javasymbolsolver#342]
Hi, I'm new to either JavaParser or JavaSymbolSolver and i would like to ask this question to you.
```java
    if (isFileFound) {

                byte[] encoded = Files.readAllBytes(Paths.get(path.getAbsolutePath()));
                String s =new String(encoded);
                
                CompilationUnit cu = new CompilationUnit();
                
                try {
                	System.out.println(path.getAbsolutePath());
                	cu = JavaParser.parse(in);
                } catch (Exception e) {
                    System.out.println("Exception while parsing the file : " + e.getMessage());
                } finally {
                    try {
                        in.close();
                    } catch (IOException e) {
                        System.out.println("Unable to close compilation unit");// TODO Auto-generated catch block
                        e.printStackTrace();
                    }
                }
                try{
                    new FileVisitor().visit(cu, JavaParserFacade.get(combinedTypeSolver));
                }catch(Exception e){
                    System.out.println(e);
                }
            }
```
This simple piece of code iterates over all possible java files in a directory (I took its source from question #240). 
My visit method search for MethodCallExpr and tries to solve it trough th JavaParserFacade
```java
    class FileVisitor extends VoidVisitorAdapter<Object> {
 
    public void visit(MethodCallExpr n, Object arg) {
        super.visit(n, arg);
        System.out.println("MethodCallExpr : " + n.getNameAsString());
        
        // SymbolReference raise an error when declared as <MethodDeclartion> but i can't figure out why 
        JavaParserFacade jpf = (JavaParserFacade) arg;
        SymbolReference reference = jpf.solve(n);
        
        if(reference.isSolved()) {
        	Declaration md = reference.getCorrespondingDeclaration();
        	System.out.println(md.getName());
        }else {
        	System.out.println("Not solved " + n.getNameAsString());
        }
        
        System.out.println("========================================");
    }
}
```
As obviuos as soon as the JPF is not able to solve the Expression it throws an error and when i caught it, the visit of the related AST is stopped. 
Is it possible to continue iterating over the AST even after the error has been caught?

My application does not need to resolve all possible method calls but only those which are written my sources, thus it is possible to think of an TypeResolver like this one
```java
    TypeSolver typeSolver =  new JavaParserTypeSolver(newFile("src/main/java");
```
Thanks!

**Comment by ftomassetti** [comment]
Probably JSS is failing because you have not specified where to find dependencies. Anyway, you can continue iterating if you just catch the exception in the visit method and prevent it from propagating.

**Comment by Cale-92** [comment]
Thanks for your fast answer! 

My problems now are related to the CombinedTypeSolver class. Although i've specificied the correct folders where to look for user files, some method calls are not solved at all otherwise some others are.

    public static CombinedTypeSolver typeSolver() {
		CombinedTypeSolver combinedTypeSolver = null;
		try {
			combinedTypeSolver = new CombinedTypeSolver();
			combinedTypeSolver.add(new JavaParserTypeSolver(new File("C:\\Users\\Jt\\StudioProjects\\aaf-easydiary-master\\app\\src\\main\\java\\me\\blog\\korn123")));
			/*combinedTypeSolver.add(new JavaParserTypeSolver(new File("C:\\Users\\Jt\\StudioProjects\\aaf-easydiary-master\\app\\src\\main\\java\\me\\blog\\korn123\\commons\\constants")));
			combinedTypeSolver.add(new JavaParserTypeSolver(new File("C:\\Users\\Jt\\StudioProjects\\aaf-easydiary-master\\app\\src\\main\\java\\me\\blog\\korn123\\commons\\utils")));
			combinedTypeSolver.add(new JavaParserTypeSolver(new File("C:\\Users\\Jt\\StudioProjects\\aaf-easydiary-master\\app\\src\\main\\java\\me\\blog\\korn123\\easydiary\\activities")));
			combinedTypeSolver.add(new JavaParserTypeSolver(new File("C:\\Users\\Jt\\StudioProjects\\aaf-easydiary-master\\app\\src\\main\\java\\me\\blog\\korn123\\easydiary\\adapters")));
			combinedTypeSolver.add(new JavaParserTypeSolver(new File("C:\\Users\\Jt\\StudioProjects\\aaf-easydiary-master\\app\\src\\main\\java\\me\\blog\\korn123\\easydiary\\chart")));
			combinedTypeSolver.add(new JavaParserTypeSolver(new File("C:\\Users\\Jt\\StudioProjects\\aaf-easydiary-master\\app\\src\\main\\java\\me\\blog\\korn123\\easydiary\\fragments")));
			combinedTypeSolver.add(new JavaParserTypeSolver(new File("C:\\Users\\Jt\\StudioProjects\\aaf-easydiary-master\\app\\src\\main\\java\\me\\blog\\korn123\\easydiary\\googledrive")));
			combinedTypeSolver.add(new JavaParserTypeSolver(new File("C:\\Users\\Jt\\StudioProjects\\aaf-easydiary-master\\app\\src\\main\\java\\me\\blog\\korn123\\easydiary\\helper")));
			combinedTypeSolver.add(new JavaParserTypeSolver(new File("C:\\Users\\Jt\\StudioProjects\\aaf-easydiary-master\\app\\src\\main\\java\\me\\blog\\korn123\\easydiary\\models")));
			combinedTypeSolver.add(new JavaParserTypeSolver(new File("C:\\Users\\Jt\\StudioProjects\\aaf-easydiary-master\\app\\src\\main\\java\\me\\blog\\korn123\\easydiary\\plagiarism")));
			combinedTypeSolver.add(new JavaParserTypeSolver(new File("C:\\Users\\Jt\\StudioProjects\\aaf-easydiary-master\\app\\src\\main\\java\\me\\blog\\korn123\\easydiary\\viewpagers")));*/
			
			combinedTypeSolver.add(new JarTypeSolver("C:\\Users\\Jt\\.m2\\repository\\org\\apache\\commons\\commons-lang3\\3.7\\commons-lang3-3.7.jar"));
			combinedTypeSolver.add(new JarTypeSolver("C:\\Users\\Jt\\.m2\\repository\\org\\bouncycastle\\bcprov-jdk15on\\1.58\\bcprov-jdk15on-1.58.jar"));
			//combinedTypeSolver.add(new JarTypeSolver("C:\\Users\\Jt\\AppData\\Local\\Android\\sdk\\platforms\\android-25\\android.jar"));
			// combinedTypeSolver.add(new JavaParserTypeSolver(new File("C:\\Users\\Jt\\StudioProjects\\aaf-easydiary-master\\app\\src\\main\\java\\me\\blog\\korn123\\easydiary\\viewpagers")));
			// combinedTypeSolver.add(new JavaParserTypeSolver(new File("C:\\Users\\Jt\\StudioProjects\\aaf-easydiary-master\\app\\src\\main\\java\\me\\blog\\korn123\\easydiary\\viewpagers")));
			// combinedTypeSolver.add(new JavaParserTypeSolver(new File("C:\\Users\\Jt\\StudioProjects\\aaf-easydiary-master\\app\\src\\main\\java\\me\\blog\\korn123\\easydiary\\viewpagers")));
			// combinedTypeSolver.add(new JavaParserTypeSolver(new File("C:\\Users\\Jt\\StudioProjects\\aaf-easydiary-master\\app\\src\\main\\java\\me\\blog\\korn123\\easydiary\\viewpagers")));
			combinedTypeSolver.add(new ReflectionTypeSolver());

			/*new JarTypeSolver("C:\\Users\\Jt\\.m2\\repository\\commons-io\\commons-io\\2.6\\commons-io-2.6.jar"),
			new JarTypeSolver("C:\\Users\\Jt\\.m2\\repository\\com\\github\\javaparser\\javaparser-core\\3.3.0\\javaparser-core-3.3.0.jar"),
			new JarTypeSolver("C:\\Users\\Jt\\.m2\\repository\\com\\github\\javaparser\\java-symbol-solver-core\\0.6.0\\java-symbol-solver-core-0.6.0.jar"),
			new JarTypeSolver("C:\\Users\\Jt\\.m2\\repository\\com\\github\\javaparser\\java-symbol-solver-logic\\0.6.0\\java-symbol-solver-logic-0.6.0.jar"),
			new JarTypeSolver("C:\\Users\\Jt\\.m2\\repository\\com\\github\\javaparser\\java-symbol-solver-model\\0.6.0\\java-symbol-solver-model-0.6.0.jar"),*/
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return combinedTypeSolver;
	}

To be more clear:

    combinedTypeSolver.add(new JavaParserTypeSolver(new File("C:\\Users\\Jt\\StudioProjects\\aaf-easydiary-master\\app\\src\\main\\java\\me\\blog\\korn123")));

This line of code is similar to "src/main/java", where i specified only the root directory of java sources.

    combinedTypeSolver.add(new JavaParserTypeSolver(new File("C:\\Users\\Jt\\StudioProjects\\aaf-easydiary-master\\app\\src\\main\\java\\me\\blog\\korn123\\commons\\utils")));

As opposite, this line and others similar, specify the exact structure of the project thus they point directly to java sources. 

The only method calls correctly solved are method declarations write in the "commons" directory sources, instead others are not.

Is this CombinedTypeSolver instantiated right? Is there the possibility to print information of the solver at runtime?
