### ISSUE TITLE
Trying rultor

### ISSUE THREAD

**Issue by ftomassetti** [javaparser/javasymbolsolver#35]
@rultor release, tag is `0.2`

**Comment by ftomassetti** [comment]
@rultor release, tag is 0.2

**Comment by ftomassetti** [comment]
@rultor release, tag is `0.2`

**Comment by ftomassetti** [comment]
@rultor release, tag is `0.2`

**Comment by ftomassetti** [comment]
Giving up rultor :D

**Comment by matozoid** [comment]
Cool, but why? :D

**Comment by ftomassetti** [comment]
It was one of my vain attempts to make the release easier...
