### ISSUE TITLE
Removal of 2 ExpressionStmt's associated to same parent fails when using LexicalPreserving CompilationUnit

### ISSUE THREAD

**Issue by Sebsen** [javaparser/javasymbolsolver#358]
Hey Guys, I have found your Project some days ago and appreciate it very much, thanks for that!

After using it and playing around with it for several days now, I have following issue:

For testing purposes I have declared following Java test class (to prove correct type resolution):

    `   
    import org.slf4j.LoggerFactory;
    import xxx.Logger;
    import xxx.MessageLogger;

    public class ComplexClass {

    private static final Logger logger = MessageLogger.instance();
    private static final org.slf4j.Logger LOGGER = LoggerFactory.getLogger(ComplexClass.class);

    public void print(final Object pObject) {
        if (pObject instanceof String) {
            print((String) pObject);
        } else if (pObject instanceof Exception) {
            print((Exception) pObject);
        }
    }

    public void print(final Exception pExceptionToLog) {
        logger.error(pExceptionToLog); // Correctly resolved for removal
        org.slf4j.Logger logger = LOGGER;
        logger.error("Error!", pExceptionToLog);
        ComplexClass.logger.error("Blah"); // Correctly resolved for removal
        logger.error("Blah");
    }`
And following Code to resolve the changes:

    `    
    private void viaMethodCalls2(final CompilationUnit pCompilationUnit, final TypeSolver pTypeSolver) {
            if (trustImportStatements && !doImportsContainTargetType(pCompilationUnit, targetType)) { // targetType -> Saved as field and in this case xxx.Logger.class
                return;
            }

            final Set<FieldDeclaration> matchingFieldDeclarations = resolveFieldDeclarations(pCompilationUnit, targetType);

            final List<MethodDeclaration> methodsToProcess = Navigator.findAllNodesOfGivenClass(pCompilationUnit, MethodDeclaration.class);
            methodsToProcess.forEach(m -> {
                // Process every method in class from bottom to up
                final List<Node> nodesToRemove = Lists.reverse(m.findFirst(BlockStmt.class).get().getChildNodes()).stream()
                        .filter(child -> process(child, matchingFieldDeclarations, targetType, pTypeSolver)).collect(Collectors.toList());
                
                for (Node node : nodesToRemove) {
                    node.remove();
                }
            });
            matchingFieldDeclarations.forEach(FieldDeclaration::remove);
            removeImport(pCompilationUnit, targetType);
        }`
The code is able to detect the correct lines of Code which should be removed (amazing!) and thus should be able to remove it. Unluckily it Fails to remove the second node! This is because after the removal of the first node the parent node for both nodes is nulled. And this is why the Node::remove method is not able to succeed on the second node.

After Debugging a little bit I noticed it is because of the "PropagatingAstObserver" - observer added by Setting up the parsed compilation unit with the LexicalPreservingPrinter.
Technically the error occurs on:

    'LexicalPreservingPrinter.concreteListChange(line:192) -> LexicalDifferenceCalculator.calculateListRemovalDifference(line:93) -> LexicalDifferenceCalculator.calculatedSyntaxModelAfterListRemoval(line:290) -> LexicalDifferenceCalculator.calculatedSyntaxModelForNode(line:161) -> ListRemovalChange.getValue(line:28)'

After "addAll" is called the parentNode for both "nodesToRemove" is nulled and this is the Point after which any other removal of nodes will (probably) fail - at least in my scenario. Unluckily the Code is quite complex at this Point and hiding a lot of Information so I cannot go deeper into it nor suggest any other solution.

The Code for Setting up the compilation unit Looks like this:

    'public static Pair<File, CompilationUnit> createPreservingCompilationUnit(final File pFromFile, final TypeSolver pTypeSolver) throws FileNotFoundException {
        JavaSymbolSolver symbolResolver = new JavaSymbolSolver(pTypeSolver);
        JavaParser.getStaticConfiguration().setSymbolResolver(symbolResolver);
        return new Pair<>(pFromFile, LexicalPreservingPrinter.setup(JavaParser.parse(pFromFile)));
    }'

Hope you guys still work on it and that this helps you when having a look on it (and to fix? this). Thanks!

**Comment by Sebsen** [comment]
This also happens when adding new elements to a parsed node with following Code:

> 

    `
    public void notWorking(final List<ExpressionStmt> pExpressionsToProcess) {
        for (final ExpressionStmt n : pExpressionsToProcess) {
            Optional<BlockStmt> parent = n.findParent(BlockStmt.class);
            parent.ifPresent(surroundingBlock -> {
                Optional<MethodCallExpr> firstContainedMethodCall = n.findFirst(MethodCallExpr.class);
                if (firstContainedMethodCall.isPresent()) {
                    final MethodCallExpr methodCallExpr = new MethodCallExpr();
                    methodCallExpr.setName(firstContainedMethodCall.get().getName());
                    methodCallExpr.setArguments(firstContainedMethodCall.get().getArguments());
                    surroundingBlock.addStatement(methodCallExpr);
                }
            });
        }
    }
`

The above Code only adds one element (by passing a list with size of 2 as an argument). The following Workaround Code (correctly) adds 2 Elements - as desired/ expected:

> 
    `
    public void working(final List<ExpressionStmt> pNodesToProcess) {
        // Workaround to add multiple children from same node in LexicalPreserving printer => Save former parent
        Optional<BlockStmt> parent = Optional.empty();
        for (final ExpressionStmt n : pNodesToProcess) {
            parent = parent.isPresent() ? parent : n.findParent(BlockStmt.class);
            parent.ifPresent(surroundingBlock -> {
                Optional<MethodCallExpr> firstContainedMethodCall = n.findFirst(MethodCallExpr.class);
                if (firstContainedMethodCall.isPresent()) {
                    final MethodCallExpr methodCallExpr = new MethodCallExpr();
                    methodCallExpr.setName(firstContainedMethodCall.get().getName());
                    methodCallExpr.setArguments(firstContainedMethodCall.get().getArguments());
                    surroundingBlock.addStatement(methodCallExpr);
                }
            });
        }
    }
`

**Comment by ftomassetti** [comment]
This bug is something we should fix in JavaParser, not JavaSymbolSolver but this issue is fine. Thanks for reporting this one, I will keep you posted as soon as I find the time to work on this one

**Comment by Sebsen** [comment]
Oh yeah of Course this has actually nothing to do with solving the Symbols. Thank you for having a look on it anyways!

**Comment by matozoid** [comment]
Moved to the right project
