### ISSUE TITLE
Anonymous classes supported?

### ISSUE THREAD

**Issue by bennewi** [javaparser/javasymbolsolver#360]
This project looks very promising, thanks for the great work.

I have an issue while resolving symbols this and super inside anonymous classes, when retrieved via visitors accepting type MethodCallExpr.

For example
```
        Dialog dee = new java.awt.Dialog((java.awt.Dialog)null) {
            @Override
            public void setTitle(String s) {
                if (s == null) {
                    this.setTitle("Day");
                    super.setTitle("Night");
                    setTitle("Twilight");
                }
            }
        };

```

javasymbolsolver does great until it hits this code. When I run 

```
javaParserFacade.solveMethodAsUsage(n).declaringType().getQualifiedName()
```

from a public void visit(MethodCallExpr n, JavaParserFacade javaParserFacade) method I get:

for this.setTitle: java.lang.UnsupportedOperationException: CorrespondingDeclaration not available for unsolved symbol.

for super.setTitle: java.lang.RuntimeException: Method 'setTitle' cannot be resolved in context super.setTitle("Night") 

for setTitle:java.lang.UnsupportedOperationException: CorrespondingDeclaration not available for unsolved symbol.

**Comment by ftomassetti** [comment]
Hi Ben,
thank you for your nice words and for reporthing this issue. I think that it is not a local class but an anonymous class.

```
void foo() {
   class A { } // local class
   new A() { } 
   Object foo = new Object { } // anonymous class
}
```

The qualified name could not work because local classes and anonymous classes have not a proper qualified name I think. Anyway it seems there is a bug because should be at most `getQualifiedName` that fails and not `solveMethodAsUsage`

**Comment by bennewi** [comment]
Fixed, thank you. 

What is the expected behavior of a type resolver when it successfully resolves a type as anonymous?

**Comment by ftomassetti** [comment]
No, I think we have a bug. What I am saying is that once we solve the bug still the resolved symbol could not have a qualified name because qualified name are well defined for types different from local classes and anonymous classes.

**Comment by matozoid** [comment]
Looks like this one: https://github.com/javaparser/javaparser/issues/1599
