### ISSUE TITLE
fail if a type is defined in a JAR, but implements an interface defined in another JAR

### ISSUE THREAD

**Issue by bennewi** [javaparser/javasymbolsolver#362]
The lookup in `JavassistClassDeclaration` that happens in the `getInterfaces` method fails down in the `ClassPoolTail`'s `find` method ... The paths it is looking into at that point don't take the full list of JARs added to the `JarTypeSolver`s, but only looks up in the current JAR. This blows up if the Java files you are parsing contain dependencies in JARs that have interfaces in other JARs... 

Can someone fix?

**Comment by ftomassetti** [comment]
To solve this kind of problems normally we try to get just the FQN of a class or interface and do not let ASM solve it. We instead want to ask the TypeSolver to solve it. It could call different JarTypeSolvers if needed.

The error seems due to the fact that we call `ctClass.getInterfaces()`. We should instead call `ctClass.getClassFile().getInterfaces();` that returns an array of Strings, not an array of CtClass. See what we do in `solveSymbol`, in the same class.

Would be possible for you to submit a failing test? I think the fix should be relatively straightforward with a failing test.

**Comment by bennewi** [comment]
@ftomassetti sure I can submit a test, is that pushing to jss060_fixes branch? I haven't contributed to this project before

**Comment by ftomassetti** [comment]
Thank you!

The best way would be to create a new branch starting from the master branch on this project. You could call it "issue362".

If you want directions with git or github just let me know!

**Comment by bennewi** [comment]
yes please, directions even for git CLI would be helpful

**Comment by ftomassetti** [comment]
1. You need to get a recent version of the master branch of this project. Either you clone it (`git@github.com:javaparser/javasymbolsolver.git`) or you go in a version you have on disk, switch to the master branch (`git checkout master`) and get the updates (`git pull origin master`). This is assuming that origin points to `git@github.com:javaparser/javasymbolsolver.git`. You can check it by running `git remote -v`. If you do not have it you can add it, for example running `git remote add upstream git@github.com:javaparser/javasymbolsolver.git`. In this example I called it "upstream", so to get data from it you should run `git pull upstream master`
2. At this point you can create a new branch: `git checkout -b issue362`
3. Now you add the test
4. You use `git status` to check what you have changed, `git add <FILENAME>` to include the file in the next commit, `git commit -m "<DESCRIPTION OF YOUR CHANGES>"` to create the commit, `git push <YOUR FORK> issue362` to send the branch to your fork.
5. If you have sent changes before you should have already your fork. If you don't let me know and I will guide you to create one. Once you have the branch in your fork, if you visit this project (https://github.com/javaparser/javasymbolsolver) it should show you a yellow message suggesting you to create a Pull Request. Follow the direction of that message and you are done

**Comment by fvanham** [comment]
See also #326, which I think is the same defect.

**Comment by matozoid** [comment]
Moved this to the new project location.
