### ISSUE TITLE
UnaryExpr failing to resolve BITWISE_COMPLEMENT operator

### ISSUE THREAD

**Issue by jjbr** [javaparser/javasymbolsolver#366]
While trying to resolve the type of an expression to which I applied the unary bitwise complement operator, an exception is thrown. In fact the TypeExtractor doesn't currently handle bitwise complement. See: https://github.com/javaparser/javasymbolsolver/blob/678dce3c4df8fd8646164d731f0557b0d7f31ca1/java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/TypeExtractor.java#L337-L352

One can simply test this with e.g.:
`int i = 1;
int j = ~i;`

Is this per design or was something perhaps forgotten to be handled?

**Comment by ftomassetti** [comment]
It was simply forgotten to be handled :)

**Comment by matozoid** [comment]
Moved to new project location
