### ISSUE TITLE
Resolving types in MethodCallExpr

### ISSUE THREAD

**Issue by inah** [javaparser/javasymbolsolver#367]
Recently started using jss and I am trying to resolve MethodCallExpr for the class below:
package analysis.vcs;
public class Car extends MotorVehicle {
	public Car(String name){
		super(name);
		setNowheels(4);
	}
}

Here is my code: 
public class NodeTypeFinder {
	static class NodeTypeVisitor extends VoidVisitorAdapter<JavaParserFacade> {

        @Override
        public void visit(MethodCallExpr n, JavaParserFacade javaParserFacade) {
            super.visit(n, javaParserFacade);
            System.out.println(n.toString() + " has type " + javaParserFacade.getType(n).describe());
            if (javaParserFacade.getType(n).isReferenceType()) {
                for (ReferenceType ancestor : javaParserFacade.getType(n).asReferenceType().getAllAncestors()) {
                    System.out.println("Ancestor " + ancestor.describe());
                }
            }
        }
    }
}

But I get runtime exception indicating it is unable to resolve the inherited class:
Exception in thread "main" UnsolvedSymbolException{context='unknown', name='MotorVehicle', typeSolver=null}

Any help in figuring this out will be greatly appreciated.

**Comment by fvanham** [comment]
1. Did you load the TypeSolver on the JavaParserFacade? E.g. try via `JavaParserFacade.get( ts ).getType( n )` where `ts` is your `TypeSolver` instance.
2. If so does your Typesolver have access to the jars and or /src directories? You need to register these explicitly on the TypeSolver. See my small example in issue #365 for code.

**Comment by inah** [comment]
Thanks, that was really useful. It turned out that I was not setting the directory path rightly.
