### ISSUE TITLE
JavaParserFacade for ClassOrInterfaceType

### ISSUE THREAD

**Issue by sranger** [javaparser/javasymbolsolver#369]
So, similarly to issue 150, I'm attempting to get the fully qualified names for the extending and implementing classes in a source file. However, when it gets to a declaration that either is ambiguous or is an inner class of another class it seems to get confused and return the wrong results.

I'm currently doing the following:

`typeSolverFacade.getSymbolSolver().solveType(((ClassOrInterfaceType) type).getElementType()).getQualifiedName()`

but when I have a class such as

`public class MyClass extends OtherClass.InnerClass`

It seems to search for OtherClass and finds it correctly but when it then searches for InnerClass I get an UnsolvedSymbolException. Also, some classes within tests that are anonymously created it seems to give the package of the test but not of the actual class being anonymously created. ie.

`MyClass.myTest() {
   new OtherClass.InnerClass();
}`

I get something like `my.class.package.InnerClass` instead of `other.class.package.OtherClass.InnerClass`

Thanks for the help!
Stephen

**Comment by ftomassetti** [comment]
**Please note that JavaSymbolSolver has been merged into JavaParser, so from now on all the issues should be opened there**

This seems a bug, marking it as such

**Comment by ftomassetti** [comment]
A failing test case would help getting this one solved more quickly

**Comment by sranger** [comment]
I will try to throw together an example sometime this morning. Thanks for the quick reply.

**Comment by ftomassetti** [comment]
Thank you for the report

**Comment by sranger** [comment]
I think this is showing off the same behavior. Let me know if it's just something weird I'm doing or if you think I didn't capture exactly what's going on. OtherClass.InnerClass seems to think it extends itself and ThirdClass.InnerClass throws an UnsolvedSymbolException when attempting to check extended types on its inner class.

[JavaTypeSolverIssue369.zip](https://github.com/javaparser/javasymbolsolver/files/1657204/JavaTypeSolverIssue369.zip)

**Comment by matozoid** [comment]
Moved to new project location.
