### ISSUE TITLE
Static method solving problem

### ISSUE THREAD

**Issue by seoj135** [javaparser/javasymbolsolver#370]
Hello. When I tried to resolve methodcallexpr, I found some bug. 
This is on 0.6.3.

1. Call Static Function on Iterable, ForeachStmt problem.
MethodCallExprContext line 157: context return null. So It Throw RuntimeException
I guess some errors on solveType() function on StatementContext(Wrapped BlockStmt).
Here is target project from git: https://github.com/davidar/lljvm
and positions is src/lljvm/runtime/Function.java line 22.

TypeSolver Settings: 
   ReflectionTypeSolver
   JavaParserTypeSolver(Root of project)
   JavaParserTypeSolver(Root of Java base libraries, I zipped out it to my custom directory)

2. visit NameExpr problem.
So To find the solution to the first bug, I make some short code and found another bug.

Here is my code:

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;

import com.github.javaparser.JavaParser;
import com.github.javaparser.ParserConfiguration;
import com.github.javaparser.ast.CompilationUnit;
import com.github.javaparser.ast.expr.MethodCallExpr;
import com.github.javaparser.ast.expr.NameExpr;
import com.github.javaparser.ast.visitor.VoidVisitorAdapter;
import com.github.javaparser.resolution.declarations.ResolvedMethodDeclaration;
import com.github.javaparser.resolution.types.ResolvedType;
import com.github.javaparser.symbolsolver.JavaSymbolSolver;
import com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade;
import com.github.javaparser.symbolsolver.resolution.typesolvers.CombinedTypeSolver;
import com.github.javaparser.symbolsolver.resolution.typesolvers.JavaParserTypeSolver;
import com.github.javaparser.symbolsolver.resolution.typesolvers.ReflectionTypeSolver;

public class test {
	@SuppressWarnings({ "unchecked", "rawtypes" })
	public static void main(String[] args) {
		String code = 
			"public class A { " + 
				"public int FUNC() { Class<?> cls = null; if(cls == null) return 0; else { B.FUNC3(cls); return 1;} } " +
				"public void FUNC2(Class<?> arg) { return; }" +
			"}" + 
			"class B {" + 
				"public static void FUNC3(Class<?> arg) { return; }" +
			"}" +
			"";
		File file = new File("A.java");
		try {
			file.createNewFile();
			FileWriter fw = new FileWriter(file);
			fw.write(code);
			fw.flush();
			fw.close();
		} catch (IOException e) {
			e.printStackTrace();
		}
		
		CombinedTypeSolver localCts = new CombinedTypeSolver();
		localCts.add(new ReflectionTypeSolver());
		localCts.add(new JavaParserTypeSolver(file.getAbsoluteFile().getParentFile()));
		
		ParserConfiguration parserConfiguration = new ParserConfiguration().setSymbolResolver(new JavaSymbolSolver(localCts));
		JavaParser.setStaticConfiguration(parserConfiguration);
		
		CompilationUnit cu = JavaParser.parse(code);
		cu.accept(new VoidVisitorAdapter() {
			public void visit(NameExpr n, Object arg) {				
				ResolvedType type = JavaParserFacade.get(localCts) .getType(n);
				super.visit(n, args);
			}
			public void visit(MethodCallExpr n, Object arg) {
				ResolvedMethodDeclaration decl = JavaParserFacade.get(localCts).solve(n).getCorrespondingDeclaration();
				super.visit(n, args);       // <---------- bug is occur.
                                // Exception in thread "main" UnsolvedSymbolException{context='Solving B', name='B', typeSolver=null}
			}
		}, null);
	}
}

3. How to fix UnsolvedSymbolException?
checking on !ref.isSolved()

**Comment by matozoid** [comment]
Hi! The symbol solver is now part of main project, so could you please open this issue over there? https://github.com/javaparser/javaparser/issues

**Comment by seoj135** [comment]
Oh.. Ok then I test with newest version again.
and close or reopen it at main project
