### ISSUE TITLE
Solve for symbol in scope that is of a given type

### ISSUE THREAD

**Issue by peterkt2000** [javaparser/javasymbolsolver#373]
Thank you for your work on the symbol solver. Does the symbol solver support the following use case: 

Given a type (e.g., a class or interface type), find the symbol in scope (e.g., variable declaration, method parameter, etc.) that is of that type. The search would start from a given node in the AST (e.g., a statement in a method). This could use the same scoped search algorithm already in place.

Example Code Being Analysed:

public method1(MyClass object1) {
   statement1;
   statement2;
   for (int x = 0; x<something;x++) {
      statement3;
   }
}

Example Usage:

SymbolReference<?> s = JavaParserFacade.get(typeSolver).getSymbolSolver().solveSymbol("org.abc.MyClass", statement3Node)

... s would return the parameter in the method declaration in this case. It could come from many places of course, but I'm looking for the resolved reference that's in scope. 

From a language engineering perspective, do you see any issues with this use case?

**Comment by matozoid** [comment]
Hi! This project has been deprecated, can you post your question here --> https://github.com/javaparser/javaparser/issues pleas?

**Comment by peterkt2000** [comment]
yes, will do. Thank you.
