### ISSUE TITLE
How to convert a NameExpr to Type?

### ISSUE THREAD

**Issue by penelope24** [javaparser/javasymbolsolver#375]
I want to feed a NameExpr into convertToUsage(), but there is no getType() in nameExpr, what can I do?

**Comment by matozoid** [comment]
Hi! Can you move this to https://github.com/javaparser/javaparser ? The projects have been integrated.

**Comment by penelope24** [comment]
@matozoid sure but actually I've solved this problem, so should I just close this issue?

**Comment by matozoid** [comment]
Sure, go ahead!
