### ISSUE TITLE
JavaParserFacade.solve(NameExpr) not working for Parameter of CatchClause

### ISSUE THREAD

**Issue by mlangkabel** [javaparser/javasymbolsolver#46]
When using the `JavaParserFacade` to solve the NameExpr of a variable that has been defined as the parameter of a catch clause it does not seem to be resolved. When looking at the `JavaParserFactory.getContext()` I don't see something like a `CatchClauseContext`. Is that one missing at the moment? Or is this something that's intended?

**Comment by ftomassetti** [comment]
Another good news: also this one seems to work. I added a test to prevent from regression and discovered a small issue in JavaParserParamaterDeclaration in the process.
