### ISSUE TITLE
IllegalStateException when using raw type instead of parameterized type

### ISSUE THREAD

**Issue by mlangkabel** [javaparser/javasymbolsolver#68]
Consider the following code:
```
public class Test{
  class A <T> {
  }
  
  void foo() {
    A a = null;
    List<A<?>> l = null;
    l.add(a);
  }
}
```

Solving the call to `l.add(a);` throws an `IllegalStateException` because the method's expected parameter and the provided argument have a different amount of type arguments.

**Comment by ftomassetti** [comment]
This has been fixed in #69
