### ISSUE TITLE
Measure coverage

### ISSUE THREAD

**Issue by ftomassetti** [javaparser/javasymbolsolver#79]
We should start using some coverage measure

**Comment by mlangkabel** [comment]
Do you mean measuring how much of the JavaParser codebase can be solved correctly?

**Comment by ftomassetti** [comment]
No, just measuring how much of our code is executed when running tests

**Comment by andreybleme** [comment]
Hey @ftomassetti how can I help?
The idea is to use some UT coverage tool to check the code coverage?

**Comment by ftomassetti** [comment]
Hi Andrey, thanks for the offer!

I do not know what a UT tool is but ideally I would like to have something
like coveralls.io which calculate the coverage at each push. Otherwise just
something that we can run as a Gradle task locally to figure out which
lines are not covered by tests.

**Comment by andreybleme** [comment]
@ftomassetti Hmm got your point now!
So, I can add a sonar config file on project, and create a Gradle task locally to check test coverage. 

What do you think about it? :+1: or :-1:

**Comment by ftomassetti** [comment]
works for me if I can run it using gradle and I do not need to install a lot of stuff to run it

**Comment by ftomassetti** [comment]
We should check on JavaParser, now that the projects have been merged
