### ISSUE TITLE
Verify that a variadic parameter is recognized as of array type

### ISSUE THREAD

**Issue by ftomassetti** [javaparser/javasymbolsolver#84]

**Comment by ccreeten** [comment]
Not sure if these are related, so I'm asking here. I have some issues getting the detection of method call types to work when they have a variadic parameter. Maybe I'm doing something wrong?

A simple example of a failing test:
``` java
@Test
public void variadicIssue() throws ParseException {
  final CompilationUnit cu = parseSample("VariadicIssue");
  final MethodCallExpr methodCall = Navigator.findMethodCall(cu, "variadicMethod");

  final JavaParserFacade javaParserFacade = JavaParserFacade.get(new ReflectionTypeSolver());
  final Type type = javaParserFacade.getType(methodCall);
  assertEquals(String.class.getCanonicalName(), type.asReferenceType().getQualifiedName());
}
```
Source of VariadicIssue:
```java
public class VariadicIssue {

  public static void main(String[] args) {
     variadicMethod(true, 1, 2, 3);
  }

  static String variadicMethod(boolean b, int... ints) {
    return "";
  }
}
```
This throws an UnsupportedOperationException.

Also, in a project I'm working on, I'm having problems with it. Using the reflection type solver combined with the jar type solver, I get an exception that ReferenceType is not an Array, thrown at com.github.javaparser.symbolsolver.model.typesystem.Type.asArrayType(Type.java:101).

It is a two parameter method, a reference type and a varargs. The reference type is not an array. If you want, I'll try to make a simple test for it.

One question I have though, after a quick glance at the source, is why in the JavassistMethodDeclaration class the method
```java
@Override
public ParameterDeclaration getParam(int i) {
   try {
    boolean variadic = false;
    if ((ctMethod.getModifiers() & javassist.Modifier.VARARGS) > 0) {
      variadic = i == (ctMethod.getParameterTypes().length - 1);
    }
    if (ctMethod.getGenericSignature() != null) {
      SignatureAttribute.MethodSignature methodSignature = SignatureAttribute.toMethodSignature(ctMethod.getGenericSignature());
      SignatureAttribute.Type signatureType = methodSignature.getParameterTypes()[i];
      return new JavassistParameterDeclaration(JavassistUtils.signatureTypeToType(signatureType, typeSolver, this), typeSolver, variadic);
     } else {
      return new JavassistParameterDeclaration(ctMethod.getParameterTypes()[0], typeSolver, variadic);
     }
   } catch (NotFoundException e) {
     throw new RuntimeException(e);
   } catch (BadBytecode badBytecode) {
     throw new RuntimeException(badBytecode);
   }
}
```	
the last return returns a parameter declaration always for the first type?

**Comment by ftomassetti** [comment]
Hi @ccreeten 
Thank you very much for this bug report: it is outstanding!

We recently have done a huge refactor for JavaSymbolSolver and we introduced a couple of issue. I resolved the one for variadic method types (there was an issue in the code that infer generic type parameters when invoked for variadic values).

Also very good catch with the problem in JavassistMethodDeclaration!

You are the best user ever, I felt compelled to add your name in the Readme. Thanks!

**Comment by ccreeten** [comment]
Thanks for your appreciation and words, way too kind! 

The first case is now working, awesome! For the second case, I got one step closer but it stumbled upon an UnsupportedOperationException this time, thrown by the resolveTypeVariables method in the JavassistMethodDeclaration class. I don't know if it is intentional, or just something to do, but I fixed it locally by implementing it like
```java
return new MethodUsage(this);
```
and now it is all working for me! I don't know if I've missed or didn't consider things, that is why I comment it here again.

Thanks and keep up the good work!

**Comment by ftomassetti** [comment]
Unfortunately that would not work always because we need to resolve some type variables as we do in the case of JavaParserMethodDeclaration. I therefore extracted the common logic in a separate class and reused in the case of JavassistMethodDeclaration. I just committed this to master.

By the way, would it help you to have a new release of this library with these fixes on Maven central?

**Comment by ccreeten** [comment]
Yea, I looked at the JavaParser implementation not so long ago and figured as much :smiley: 

It is all working great now! I'm not in that much of a hurry for a release, take your time. Thanks for the fixes and quick responses!

**Comment by ftomassetti** [comment]
That was solved
