### ISSUE TITLE
Verify Type inference works as described in the JLS

### ISSUE THREAD

**Issue by ftomassetti** [javaparser/javasymbolsolver#9]
See https://docs.oracle.com/javase/specs/jls/se8/html/jls-18.html

**Comment by ftomassetti** [comment]
The plan is to doing that through testing. We should look into the documentation and generate as many tests as possible to certify the correct behavior.

**Comment by ftomassetti** [comment]
Basically I am looking into implementing everything as specified in https://docs.oracle.com/javase/specs/jls/se8/html/jls-18.html

It is a lot of work and it could lead to the need of adapting the API, so I am not sure I will be able to complete this one, for now it is an experiment.

**Comment by matozoid** [comment]
Well, if it needs adapting the API then that should be done, I think :-) JSS is still pre-1.0!

**Comment by ftomassetti** [comment]
Yes, it is just that it could be a big change... so let's see if the effort results to be herculean or if it is possible to find intermediate steps where everything keeps working until we eventually have the new implementation used consistently

**Comment by ftomassetti** [comment]
Some code has been merged but it needs to be completed and integrated with the existing API

**Comment by ftomassetti** [comment]
We will continue this in JP
