### ISSUE TITLE
Rename the project

### ISSUE THREAD

**Issue by ftomassetti** [javaparser/javasymbolsolver#99]
The project is currently named _java-symbol-solver_ 
Should we rename it to:
* JavaSymbolSolver
* SymbolSolver
* keep it like it is
* rename it in another way

**Comment by matozoid** [comment]
As long as it is a separate project I think the current name is fine.

**Comment by ftomassetti** [comment]
I just find it confusing to have a separate style. When I write about java-symbol-solver I tend to call it JavaSymbolSolver if I use the name JavaParser in the same paragrah

**Comment by matozoid** [comment]
Oh, yes, do remove the dashes.

**Comment by ftomassetti** [comment]
I will rename the Github project, while I think that the "maven name" should keep the dashes

**Comment by ftomassetti** [comment]
Done :)
